export const generalStats = [
  {
    deleted: false,
    createdAt: {
      seconds: 1668531487,
      nanoseconds: 123000000,
    },
    uname: "adsturza",
    tagId: "laQPWJhUFidDn0LGR35F",
    days: [
      {
        day: "2020-12-31",
        chapters: [
          {
            proposals: 1,
            nodes: 1,
            title: "Introduction to data science in python",
            links: 1,
            questions: 0,
            node: "DyGtZvav7lWXoWlLkUgH",
            agreementsWithInst: 1,
            questionProposals: 1,
            newNodes: 0,
            disagreementsWithInst: 0,
          },
        ],
      },
      {
        day: "2021-01-03",
        chapters: [
          {
            questionProposals: 0,
            disagreementsWithInst: 0,
            title: "Introduction to data science in python",
            node: "DyGtZvav7lWXoWlLkUgH",
            nodes: 2,
            links: 5,
            agreementsWithInst: 1,
            newNodes: 1,
            questions: 0,
            proposals: 5,
          },
          {
            nodes: 1,
            questions: 1,
            agreementsWithInst: 1,
            newNodes: 1,
            questionProposals: 1,
            node: "Z9aJUE2A1TjjHal6DFIK",
            disagreementsWithInst: 0,
            proposals: 1,
            title: "Applied machine learning in python",
            links: 1,
          },
        ],
      },
      {
        chapters: [
          {
            title: "Introduction to data science in python",
            nodes: 1,
            newNodes: 0,
            node: "DyGtZvav7lWXoWlLkUgH",
            links: 0,
            disagreementsWithInst: 0,
            agreementsWithInst: 1,
            questions: 0,
            questionProposals: 1,
            proposals: 3,
          },
        ],
        day: "2021-01-04",
      },
    ],
    updatedAt: {
      seconds: 1668531487,
      nanoseconds: 123000000,
    },
  },
  // {
  //   deleted: false,
  //   createdAt: {
  //     seconds: 1668350393,
  //     nanoseconds: 717000000,
  //   },
  //   uname: "hayounki",
  //   tagId: "laQPWJhUFidDn0LGR35F",
  //   days: [
  //     {
  //       chapters: [
  //         {
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           newNodes: 3,
  //           disagreementsWithInst: 3,
  //           links: 3,
  //           title: "Introduction to data science in python",
  //           nodes: 3,
  //           agreementsWithInst: 0,
  //           proposals: 4,
  //           questions: 3,
  //         },
  //         {
  //           disagreementsWithInst: 0,
  //           title: "Applied machine learning in python",
  //           node: "Z9aJUE2A1TjjHal6DFIK",
  //           proposals: 4,
  //           questions: 0,
  //           newNodes: 2,
  //           links: 2,
  //           nodes: 0,
  //           agreementsWithInst: 0,
  //         },
  //       ],
  //       day: "2020-12-31",
  //     },
  //     {
  //       day: "2021-01-02",
  //       chapters: [
  //         {
  //           newNodes: 0,
  //           title: "Introduction to data science in python",
  //           proposals: 0,
  //           nodes: 0,
  //           agreementsWithInst: 0,
  //           links: 0,
  //           disagreementsWithInst: 0,
  //           questions: 0,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //         },
  //         {
  //           questions: 0,
  //           disagreementsWithInst: 0,
  //           newNodes: 1,
  //           nodes: 0,
  //           node: "Z9aJUE2A1TjjHal6DFIK",
  //           title: "Applied machine learning in python",
  //           links: 6,
  //           agreementsWithInst: 0,
  //           proposals: 6,
  //         },
  //         {
  //           title: "Neural Networks and Deep learning",
  //           newNodes: 1,
  //           questions: 0,
  //           nodes: 1,
  //           proposals: 4,
  //           node: "j3BJLJyLhm1kM3xkC9om",
  //           agreementsWithInst: 0,
  //           disagreementsWithInst: 1,
  //           links: 2,
  //         },
  //       ],
  //     },
  //   ],
  //   updatedAt: {
  //     seconds: 1668350393,
  //     nanoseconds: 717000000,
  //   },
  // },
  {
    deleted: false,
    updatedAt: {
      seconds: 1668531487,
      nanoseconds: 138000000,
    },
    tagId: "laQPWJhUFidDn0LGR35F",
    createdAt: {
      seconds: 1668531487,
      nanoseconds: 138000000,
    },
    uname: "elijah-fox",
    days: [
      {
        chapters: [
          {
            newNodes: 0,
            node: "DyGtZvav7lWXoWlLkUgH",
            questionProposals: 0,
            nodes: 0,
            links: 1,
            proposals: 1,
            questions: 0,
            title: "Introduction to data science in python",
            disagreementsWithInst: 0,
            agreementsWithInst: 0,
          },
          {
            node: "Z9aJUE2A1TjjHal6DFIK",
            questionProposals: 1,
            proposals: 1,
            disagreementsWithInst: 0,
            newNodes: 0,
            questions: 0,
            title: "Applied machine learning in python",
            links: 0,
            agreementsWithInst: 0,
            nodes: 0,
          },
        ],
        day: "2021-01-01",
      },
      {
        chapters: [
          {
            questions: 0,
            disagreementsWithInst: 0,
            node: "DyGtZvav7lWXoWlLkUgH",
            links: 0,
            title: "Introduction to data science in python",
            proposals: 2,
            questionProposals: 2,
            agreementsWithInst: 0,
            newNodes: 0,
            nodes: 0,
          },
        ],
        day: "2021-01-03",
      },
      {
        day: "2021-01-04",
        chapters: [
          {
            agreementsWithInst: 0,
            proposals: 1,
            questions: 1,
            links: 1,
            nodes: 1,
            newNodes: 1,
            title: "Introduction to data science in python",
            disagreementsWithInst: 0,
            questionProposals: 1,
            node: "DyGtZvav7lWXoWlLkUgH",
          },
          {
            nodes: 0,
            questionProposals: 0,
            agreementsWithInst: 0,
            node: "Z9aJUE2A1TjjHal6DFIK",
            title: "Applied machine learning in python",
            newNodes: 0,
            questions: 0,
            disagreementsWithInst: 0,
            links: 0,
            proposals: 2,
          },
        ],
      },
    ],
  },
  // {
  //   tagId: "laQPWJhUFidDn0LGR35F",
  //   createdAt: {
  //     seconds: 1668531487,
  //     nanoseconds: 126000000,
  //   },
  //   days: [
  //     {
  //       chapters: [
  //         {
  //           questionProposals: 5,
  //           title: "Introduction to data science in python",
  //           proposals: 6,
  //           nodes: 6,
  //           agreementsWithInst: 2,
  //           questions: 3,
  //           links: 5,
  //           disagreementsWithInst: 4,
  //           newNodes: 5,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //         },
  //       ],
  //       day: "2021-01-02",
  //     },
  //     {
  //       chapters: [
  //         {
  //           proposals: 1,
  //           links: 0,
  //           questionProposals: 1,
  //           questions: 0,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           nodes: 0,
  //           agreementsWithInst: 0,
  //           disagreementsWithInst: 0,
  //           title: "Introduction to data science in python",
  //           newNodes: 0,
  //         },
  //         {
  //           node: "Z9aJUE2A1TjjHal6DFIK",
  //           links: 1,
  //           nodes: 0,
  //           agreementsWithInst: 0,
  //           questions: 0,
  //           disagreementsWithInst: 0,
  //           title: "Applied machine learning in python",
  //           questionProposals: 0,
  //           proposals: 1,
  //           newNodes: 0,
  //         },
  //         {
  //           agreementsWithInst: 0,
  //           disagreementsWithInst: 0,
  //           title: "Neural Networks and Deep learning",
  //           questionProposals: 0,
  //           newNodes: 0,
  //           proposals: 1,
  //           links: 1,
  //           questions: 0,
  //           node: "j3BJLJyLhm1kM3xkC9om",
  //           nodes: 0,
  //         },
  //       ],
  //       day: "2021-01-03",
  //     },
  //   ],
  //   uname: "tallurid",
  //   updatedAt: {
  //     seconds: 1668531487,
  //     nanoseconds: 126000000,
  //   },
  //   deleted: false,
  // },
  // {
  //   updatedAt: {
  //     seconds: 1668531487,
  //     nanoseconds: 120000000,
  //   },
  //   uname: "sarahlatto",
  //   deleted: false,
  //   createdAt: {
  //     seconds: 1668531487,
  //     nanoseconds: 120000000,
  //   },
  //   tagId: "laQPWJhUFidDn0LGR35F",
  //   days: [
  //     {
  //       day: "2021-01-03",
  //       chapters: [
  //         {
  //           questions: 0,
  //           agreementsWithInst: 0,
  //           proposals: 2,
  //           disagreementsWithInst: 0,
  //           links: 2,
  //           questionProposals: 0,
  //           title: "Introduction to data science in python",
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           nodes: 0,
  //           newNodes: 0,
  //         },
  //       ],
  //     },
  //     {
  //       chapters: [
  //         {
  //           disagreementsWithInst: 0,
  //           nodes: 5,
  //           title: "Introduction to data science in python",
  //           questions: 4,
  //           newNodes: 5,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           agreementsWithInst: 3,
  //           links: 6,
  //           proposals: 6,
  //           questionProposals: 5,
  //         },
  //         {
  //           nodes: 0,
  //           disagreementsWithInst: 0,
  //           node: "Z9aJUE2A1TjjHal6DFIK",
  //           proposals: 1,
  //           questionProposals: 1,
  //           newNodes: 0,
  //           links: 1,
  //           agreementsWithInst: 0,
  //           questions: 0,
  //           title: "Applied machine learning in python",
  //         },
  //         {
  //           newNodes: 0,
  //           links: 0,
  //           disagreementsWithInst: 0,
  //           agreementsWithInst: 0,
  //           title: "Neural Networks and Deep learning",
  //           proposals: 0,
  //           node: "j3BJLJyLhm1kM3xkC9om",
  //           questionProposals: 0,
  //           nodes: 0,
  //           questions: 0,
  //         },
  //       ],
  //       day: "2021-01-05",
  //     },
  //   ],
  // },
  // {
  //   createdAt: {
  //     seconds: 1668531487,
  //     nanoseconds: 112000000,
  //   },
  //   tagId: "laQPWJhUFidDn0LGR35F",
  //   updatedAt: {
  //     seconds: 1668531487,
  //     nanoseconds: 113000000,
  //   },
  //   deleted: false,
  //   days: [
  //     {
  //       day: "2021-01-05",
  //       chapters: [
  //         {
  //           links: 0,
  //           newNodes: 0,
  //           title: "Introduction to data science in python",
  //           agreementsWithInst: 0,
  //           proposals: 2,
  //           questionProposals: 2,
  //           nodes: 0,
  //           disagreementsWithInst: 0,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           questions: 0,
  //         },
  //       ],
  //     },
  //   ],
  //   uname: "Gege Dwyer",
  // },
  // {
  //   days: [
  //     {
  //       day: "2021-01-01",
  //       chapters: [
  //         {
  //           disagreementsWithInst: 0,
  //           agreementsWithInst: 0,
  //           nodes: 0,
  //           proposals: 1,
  //           newNodes: 0,
  //           links: 1,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           title: "Introduction to data science in python",
  //           questions: 0,
  //         },
  //         {
  //           disagreementsWithInst: 0,
  //           links: 1,
  //           nodes: 0,
  //           node: "Z9aJUE2A1TjjHal6DFIK",
  //           newNodes: 1,
  //           title: "Applied machine learning in python",
  //           proposals: 2,
  //           questions: 0,
  //           agreementsWithInst: 0,
  //         },
  //         {
  //           nodes: 4,
  //           disagreementsWithInst: 1,
  //           agreementsWithInst: 3,
  //           questions: 3,
  //           newNodes: 4,
  //           title: "Neural Networks and Deep learning",
  //           proposals: 5,
  //           node: "j3BJLJyLhm1kM3xkC9om",
  //           links: 5,
  //         },
  //       ],
  //     },
  //     {
  //       chapters: [
  //         {
  //           newNodes: 0,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           links: 1,
  //           title: "Introduction to data science in python",
  //           agreementsWithInst: 0,
  //           disagreementsWithInst: 0,
  //           questions: 0,
  //           proposals: 4,
  //           nodes: 0,
  //         },
  //       ],
  //       day: "2021-01-06",
  //     },
  //     {
  //       chapters: [
  //         {
  //           questions: 0,
  //           disagreementsWithInst: 0,
  //           nodes: 0,
  //           agreementsWithInst: 0,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           title: "Introduction to data science in python",
  //           newNodes: 1,
  //           links: 1,
  //           proposals: 1,
  //         },
  //         {
  //           links: 0,
  //           node: "Z9aJUE2A1TjjHal6DFIK",
  //           agreementsWithInst: 0,
  //           proposals: 2,
  //           disagreementsWithInst: 0,
  //           title: "Applied machine learning in python",
  //           nodes: 0,
  //           newNodes: 0,
  //           questions: 0,
  //         },
  //       ],
  //       day: "2021-01-10",
  //     },
  //   ],
  //   uname: "sydlee",
  //   tagId: "laQPWJhUFidDn0LGR35F",
  //   createdAt: {
  //     seconds: 1668350393,
  //     nanoseconds: 719000000,
  //   },
  //   updatedAt: {
  //     seconds: 1668350393,
  //     nanoseconds: 719000000,
  //   },
  //   deleted: false,
  // },
  // {
  //   days: [
  //     {
  //       chapters: [
  //         {
  //           nodes: 0,
  //           proposals: 2,
  //           title: "Introduction to data science in python",
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           agreementsWithInst: 0,
  //           disagreementsWithInst: 0,
  //           questions: 0,
  //           newNodes: 0,
  //           links: 0,
  //         },
  //       ],
  //       day: "2021-01-03",
  //     },
  //     {
  //       day: "2021-01-04",
  //       chapters: [
  //         {
  //           proposals: 1,
  //           newNodes: 0,
  //           agreementsWithInst: 0,
  //           disagreementsWithInst: 0,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           questions: 0,
  //           nodes: 0,
  //           links: 0,
  //           title: "Introduction to data science in python",
  //         },
  //         {
  //           node: "Z9aJUE2A1TjjHal6DFIK",
  //           title: "Applied machine learning in python",
  //           agreementsWithInst: 0,
  //           disagreementsWithInst: 0,
  //           questions: 0,
  //           proposals: 1,
  //           nodes: 0,
  //           links: 0,
  //           newNodes: 0,
  //         },
  //       ],
  //     },
  //     {
  //       chapters: [
  //         {
  //           disagreementsWithInst: 0,
  //           links: 4,
  //           questions: 0,
  //           title: "Introduction to data science in python",
  //           proposals: 4,
  //           newNodes: 3,
  //           nodes: 1,
  //           agreementsWithInst: 1,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //         },
  //       ],
  //       day: "2021-01-07",
  //     },
  //     {
  //       chapters: [
  //         {
  //           disagreementsWithInst: 1,
  //           agreementsWithInst: 0,
  //           questions: 1,
  //           proposals: 2,
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           nodes: 1,
  //           links: 2,
  //           title: "Introduction to data science in python",
  //           newNodes: 2,
  //         },
  //         {
  //           proposals: 2,
  //           node: "Z9aJUE2A1TjjHal6DFIK",
  //           disagreementsWithInst: 0,
  //           questions: 0,
  //           agreementsWithInst: 0,
  //           newNodes: 0,
  //           nodes: 0,
  //           links: 0,
  //           title: "Applied machine learning in python",
  //         },
  //       ],
  //       day: "2021-01-08",
  //     },
  //   ],
  //   updatedAt: {
  //     seconds: 1668350393,
  //     nanoseconds: 721000000,
  //   },
  //   createdAt: {
  //     seconds: 1668350393,
  //     nanoseconds: 721000000,
  //   },
  //   uname: "adsturza",
  //   tagId: "laQPWJhUFidDn0LGR35F",
  //   deleted: false,
  // },
  // {
  //   days: [
  //     {
  //       chapters: [
  //         {
  //           node: "DyGtZvav7lWXoWlLkUgH",
  //           agreementsWithInst: 0,
  //           links: 3,
  //           title: "Introduction to data science in python",
  //           nodes: 3,
  //           proposals: 4,
  //           questions: 0,
  //           newNodes: 1,
  //           disagreementsWithInst: 2,
  //           questionProposals: 1,
  //         },
  //         {
  //           node: "Z9aJUE2A1TjjHal6DFIK",
  //           title: "Applied machine learning in python",
  //           questionProposals: 0,
  //           newNodes: 0,
  //           links: 1,
  //           agreementsWithInst: 0,
  //           disagreementsWithInst: 0,
  //           nodes: 0,
  //           questions: 0,
  //           proposals: 1,
  //         },
  //       ],
  //       day: "2020-12-31",
  //     },
  //   ],
  //   deleted: false,
  //   updatedAt: {
  //     seconds: 1668531487,
  //     nanoseconds: 129000000,
  //   },
  //   uname: "rwilmer",
  //   tagId: "laQPWJhUFidDn0LGR35F",
  //   createdAt: {
  //     seconds: 1668531487,
  //     nanoseconds: 129000000,
  //   },
  // },
];
