import { FullNodeData, FullNodesData } from "../../nodeBookTypes";

const DEFAULT_NODE_DATE = new Date("2020-01-30T03:58:24.537Z");

const BASE_NODE: FullNodeData = {
  node: "00",
  createdAt: DEFAULT_NODE_DATE,
  open: true,
  changed: true,
  wrong: false,
  updatedAt: DEFAULT_NODE_DATE,
  bookmarked: false,
  user: "max10",
  visible: true,
  isStudied: false,
  deleted: false,
  correct: false,
  nodeImage: "",
  tags: ["1Cademy"],
  comments: 0,
  contributors: {
    "1man": {
      chooseUname: false,
      fullname: "Iman YeckehZaare",
      imageUrl:
        "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2F1man_Thu%2C%2006%20Feb%202020%2016%3A26%3A40%20GMT.png?alt=media&token=94459dbb-81f9-462a-83ef-62d1129f5851",
      reputation: 24,
    },
  },
  nodeType: "Concept",
  bookmarks: 0,
  viewers: 0,
  content: "",
  aFullname: "Iman YeckehZaare",
  tagIds: [""],
  institutions: {
    "University of Michigan - Ann Arbor": {
      reputation: 27,
    },
  },
  contribNames: ["1man"],
  referenceIds: [],
  children: [],
  referenceLabels: [],
  admin: "1man",
  institNames: ["University of Michigan - Ann Arbor"],
  versions: 0,
  changedAt: DEFAULT_NODE_DATE,
  corrects: 0,
  title: "",
  maxVersionRating: 0,
  references: [],
  studied: 0,
  parents: [],
  aImgUrl:
    "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2F1man_Thu%2C%2006%20Feb%202020%2016%3A26%3A40%20GMT.png?alt=media&token=94459dbb-81f9-462a-83ef-62d1129f5851",
  wrongs: 0,
  userNodeId: "",
  nodeChangeType: "removed",
  userNodeChangeType: "removed",
  editable: false,
  left: 0,
  top: 0,
  firstVisit: DEFAULT_NODE_DATE,
  lastVisit: DEFAULT_NODE_DATE,
  choices: [],
  nodeChanges: null,
  nodeVideo: undefined,
  isTag: false,
  aChooseUname: false,
};

export const INTERACTIVE_TUTORIAL_NOTEBOOK_NODES: FullNodesData = {
  "00": {
    changed: true,
    correct: false,
    createdAt: new Date("2023-02-15T20:49:56.817Z"),
    updatedAt: new Date("2023-02-15T20:49:56.817Z"),
    deleted: false,
    isStudied: false,
    bookmarked: false,
    node: "00",
    open: true,
    user: "jn10",
    visible: true,
    wrong: false,
    aChooseUname: false,
    wrongs: 0,
    referenceLabels: [],
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-dev.appspot.com/o/ProfilePictures%2FJwguflXUHAXGBKGRxbJDnnacv132%2FThu%2C%2002%20Feb%202023%2015%3A19%3A28%20GMT_430x1300.jpeg?alt=media&token=32e515c5-a8d9-4c30-a93b-101f36577cb3",
    nodeType: "Concept",
    // adminPoints: 29,
    tags: ["1Cademy"],
    aFullname: "jj qq",
    // awards: 0,
    referenceIds: [],
    tagIds: [],
    maxVersionRating: 29,
    studied: 2,
    viewers: 2,
    institutions: {
      "University of Michigan - Ann Arbor": {
        reputation: 0,
      },
    },
    contributors: {
      jn10: {
        chooseUname: false,
        reputation: 0,
        fullname: "jj qq",
        imageUrl:
          "https://firebasestorage.googleapis.com/v0/b/onecademy-dev.appspot.com/o/ProfilePictures%2FJwguflXUHAXGBKGRxbJDnnacv132%2FThu%2C%2002%20Feb%202023%2015%3A19%3A28%20GMT_430x1300.jpeg?alt=media&token=32e515c5-a8d9-4c30-a93b-101f36577cb3",
      },
    },
    content:
      "1Cademy is a collaborative online community that supports interdisciplinary research and learning through content generation, mapping, evaluation, and practice.",
    children: [
      {
        type: "Concept",
        title: "This is a node",
        node: "01",
        label: "",
      },
    ],
    changedAt: new Date("2023-02-15T20:49:56.817Z"),
    comments: 0,
    contribNames: ["jn10"],
    corrects: 1,
    references: [],
    admin: "jn10",
    parents: [],
    versions: 1,
    nodeVideo: "",
    institNames: ["University of Michigan - Ann Arbor"],
    title: "1Cademy",
    nodeImage: "",
    userNodeId: "Tvh7IxaVAGkTATAV9RPT",
    nodeChangeType: "added",
    userNodeChangeType: "added",
    editable: false,
    left: 1350,
    top: 330.5,
    firstVisit: new Date("2023-02-15T20:49:56.817Z"),
    lastVisit: new Date("2023-02-15T20:49:56.817Z"),
    choices: [],
    nodeChanges: null,
    isTag: false,
  },
  "01": {
    node: "01",
    createdAt: new Date("2020-01-30T03:58:24.537Z"),
    open: true,
    changed: true,
    wrong: false,
    updatedAt: new Date("2023-02-23T01:56:52.894Z"),
    bookmarked: false,
    user: "max10",
    visible: true,
    isStudied: false,
    deleted: false,
    correct: false,
    nodeImage: "",
    tags: ["1Cademy"],
    comments: 0,
    contributors: {
      "1man": {
        chooseUname: false,
        fullname: "Iman YeckehZaare",
        imageUrl:
          "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2F1man_Thu%2C%2006%20Feb%202020%2016%3A26%3A40%20GMT.png?alt=media&token=94459dbb-81f9-462a-83ef-62d1129f5851",
        reputation: 24,
      },
      Grae: {
        fullname: "Gail Grot",
        reputation: 5.280000000000001,
        chooseUname: false,
        imageUrl:
          "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Fa2m8BaOOO2OrIhKGIOmz7Ly1v8q1%2FWed%2C%2009%20Dec%202020%2002%3A37%3A12%20GMT.jpg?alt=media&token=db5b7e1b-8545-4cb7-b3ee-c5d37ed62ac0",
      },
      catgrillo: {
        chooseUname: false,
        reputation: 3,
        fullname: "Catherine Grillo",
        imageUrl:
          "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FmVOVcO8zqBg83JRx1S8rXXqD0sA3%2FWed%2C%2007%20Apr%202021%2016%3A56%3A00%20GMT.jpeg?alt=media&token=1a91e810-aaa1-46ae-a83d-77b251613593",
      },
    },
    nodeType: "Concept",
    bookmarks: 0,
    viewers: 41,
    content:
      "A node is a rectangular box that represents a granular piece of information through the title and the content. Each node also has a header and a footer of buttons.",
    aFullname: "Iman YeckehZaare",
    tagIds: ["r98BjyFDCe4YyLA3U8ZE"],
    institutions: {
      "University of Michigan - Ann Arbor": {
        reputation: 27,
      },
      "San Jose State University": {
        reputation: 5.280000000000001,
      },
    },
    contribNames: ["1man", "catgrillo", "Grae"],
    referenceIds: [],
    children: [
      {
        node: "03",
        title: "1Cademy Node Components",
        type: "Concept",
        label: "",
      },
    ],
    referenceLabels: [],
    admin: "1man",
    institNames: ["University of Michigan - Ann Arbor", "San Jose State University"],
    versions: 12,
    changedAt: new Date("2022-04-08T19:48:45.868Z"),
    corrects: 8,
    title: "1Cademy Nodes",
    maxVersionRating: 4,
    references: [],
    studied: 3,
    parents: [
      {
        node: "00",
        title: "1Cademy",
        type: "Concept",
        label: "",
      },
    ],
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2F1man_Thu%2C%2006%20Feb%202020%2016%3A26%3A40%20GMT.png?alt=media&token=94459dbb-81f9-462a-83ef-62d1129f5851",
    wrongs: 3,
    userNodeId: "sVilIF7OTcYioO7J2ejM",
    nodeChangeType: "added",
    userNodeChangeType: "added",
    editable: false,
    left: 1350,
    top: 307.953125,
    firstVisit: new Date("2022-11-15T19:53:10.475Z"),
    lastVisit: new Date("2023-02-23T01:56:41.530Z"),
    choices: [],
    nodeChanges: null,
    nodeVideo: "https://youtu.be/exLS4UadfFU",
    isTag: false,
    aChooseUname: false,
    // changed: true,
    // correct: false,
    // createdAt: new Date("2023-02-15T20:49:56.817Z"),
    // updatedAt: new Date("2023-02-15T20:49:56.817Z"),
    // deleted: false,
    // isStudied: false,
    // bookmarked: false,
    // node: "01",
    // open: true,
    // user: "jn10",
    // visible: true,
    // wrong: false,
    // aChooseUname: false,
    // wrongs: 0,
    // referenceLabels: [],
    // aImgUrl:
    //   "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2F1man_Thu%2C%2006%20Feb%202020%2016%3A26%3A40%20GMT.png?alt=media&token=94459dbb-81f9-462a-83ef-62d1129f5851",
    // nodeType: "Concept",
    // // adminPoints: 29,
    // tags: ["1Cademy"],
    // aFullname: "Iman YeckehZaare",
    // // awards: 0,
    // referenceIds: [],
    // tagIds: [],
    // maxVersionRating: 29,
    // studied: 2,
    // viewers: 2,
    // institutions: {
    //   "University of Michigan - Ann Arbor": {
    //     reputation: 0,
    //   },
    // },
    // contributors: {
    //   jn10: {
    //     chooseUname: false,
    //     reputation: 0,
    //     fullname: "jj qq",
    //     imageUrl:
    //       "https://firebasestorage.googleapis.com/v0/b/onecademy-dev.appspot.com/o/ProfilePictures%2FJwguflXUHAXGBKGRxbJDnnacv132%2FThu%2C%2002%20Feb%202023%2015%3A19%3A28%20GMT_430x1300.jpeg?alt=media&token=32e515c5-a8d9-4c30-a93b-101f36577cb3",
    //   },
    // },
    // content:
    //   "A node is a single unit of information. Nodes are connected to other nodes. Together they make up a larger body of knowledge.",
    // children: [
    //   {
    //     type: "Concept",
    //     title: "This is a child node",
    //     node: "02",
    //     label: "",
    //   },
    // ],
    // changedAt: new Date("2023-02-15T20:49:56.817Z"),
    // comments: 0,
    // contribNames: ["jn10"],
    // corrects: 1,
    // references: [],
    // admin: "1man",
    // parents: [
    //   {
    //     node: "00",
    //     title: "This is a parent node",
    //     type: "Concept",
    //     label: "",
    //     // visible: true,
    //   },
    // ],
    // versions: 1,
    // nodeVideo: "",
    // institNames: ["University of Michigan - Ann Arbor"],
    // title: "This is a node",
    // nodeImage: "",
    // userNodeId: "Tvh7IxaVAGkTATAV9RPT",
    // nodeChangeType: "added",
    // userNodeChangeType: "added",
    // editable: false,
    // left: 1350,
    // top: 330.5,
    // firstVisit: new Date("2023-02-15T20:49:56.817Z"),
    // lastVisit: new Date("2023-02-15T20:49:56.817Z"),
    // choices: [],
    // nodeChanges: null,
    // isTag: false,
  },
  "02": {
    changed: true,
    correct: false,
    createdAt: new Date("2023-02-15T20:49:56.817Z"),
    updatedAt: new Date("2023-02-15T20:49:56.817Z"),
    deleted: false,
    isStudied: false,
    bookmarked: false,
    node: "02",
    open: true,
    user: "jn10",
    visible: true,
    wrong: false,
    aChooseUname: false,
    wrongs: 0,
    referenceLabels: [],
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-dev.appspot.com/o/ProfilePictures%2FJwguflXUHAXGBKGRxbJDnnacv132%2FThu%2C%2002%20Feb%202023%2015%3A19%3A28%20GMT_430x1300.jpeg?alt=media&token=32e515c5-a8d9-4c30-a93b-101f36577cb3",
    nodeType: "Relation",
    // adminPoints: 29,
    tags: ["1Cademy"],
    aFullname: "jj qq",
    // awards: 0,
    referenceIds: [],
    tagIds: [],
    maxVersionRating: 29,
    studied: 2,
    viewers: 2,
    institutions: {
      "University of Michigan - Ann Arbor": {
        reputation: 0,
      },
    },
    contributors: {
      jn10: {
        chooseUname: false,
        reputation: 0,
        fullname: "jj qq",
        imageUrl:
          "https://firebasestorage.googleapis.com/v0/b/onecademy-dev.appspot.com/o/ProfilePictures%2FJwguflXUHAXGBKGRxbJDnnacv132%2FThu%2C%2002%20Feb%202023%2015%3A19%3A28%20GMT_430x1300.jpeg?alt=media&token=32e515c5-a8d9-4c30-a93b-101f36577cb3",
      },
    },
    content:
      "A child node comes after a parent node. A child node can also be a parent node if they have their own child(ren).",
    children: [],
    changedAt: new Date("2023-02-15T20:49:56.817Z"),
    comments: 0,
    contribNames: ["jn10"],
    corrects: 1,
    references: [],
    admin: "jn10",
    parents: [
      {
        node: "01",
        title: "1Cademy Nodes",
        type: "Concept",
        label: "",
        // visible: true,
      },
    ],
    versions: 1,
    nodeVideo: "",
    institNames: ["University of Michigan - Ann Arbor"],
    title: "1Cademy Node Components",
    nodeImage: "",
    userNodeId: "Tvh7IxaVAGkTATAV9RPT",
    nodeChangeType: "added",
    userNodeChangeType: "added",
    editable: false,
    left: 1350,
    top: 330.5,
    firstVisit: new Date("2023-02-15T20:49:56.817Z"),
    lastVisit: new Date("2023-02-15T20:49:56.817Z"),
    choices: [],
    nodeChanges: null,
    isTag: false,
  },
  "03": {
    changed: true,
    correct: false,
    createdAt: new Date("2023-02-15T20:49:56.817Z"),
    updatedAt: new Date("2023-02-15T20:49:56.817Z"),
    deleted: false,
    isStudied: false,
    bookmarked: false,
    node: "03",
    open: false,
    user: "jn10",
    visible: true,
    wrong: false,
    aChooseUname: false,
    wrongs: 0,
    referenceLabels: [],
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-dev.appspot.com/o/ProfilePictures%2FJwguflXUHAXGBKGRxbJDnnacv132%2FThu%2C%2002%20Feb%202023%2015%3A19%3A28%20GMT_430x1300.jpeg?alt=media&token=32e515c5-a8d9-4c30-a93b-101f36577cb3",
    nodeType: "Concept",
    // adminPoints: 29,
    tags: ["1Cademy"],
    aFullname: "jj qq",
    // awards: 0,
    referenceIds: [],
    tagIds: [],
    maxVersionRating: 29,
    studied: 2,
    viewers: 2,
    institutions: {
      "University of Michigan - Ann Arbor": {
        reputation: 0,
      },
    },
    contributors: {
      jn10: {
        chooseUname: false,
        reputation: 0,
        fullname: "jj qq",
        imageUrl:
          "https://firebasestorage.googleapis.com/v0/b/onecademy-dev.appspot.com/o/ProfilePictures%2FJwguflXUHAXGBKGRxbJDnnacv132%2FThu%2C%2002%20Feb%202023%2015%3A19%3A28%20GMT_430x1300.jpeg?alt=media&token=32e515c5-a8d9-4c30-a93b-101f36577cb3",
      },
    },
    content:
      "A child node comes after a parent node. A child node can also be a parent node if they have their own child(ren).",
    children: [],
    changedAt: new Date("2023-02-15T20:49:56.817Z"),
    comments: 0,
    contribNames: ["jn10"],
    corrects: 1,
    references: [],
    admin: "jn10",
    parents: [
      {
        node: "01",
        title: "1Cademy Nodes",
        type: "Concept",
        label: "",
        // visible: true,
      },
    ],
    versions: 1,
    nodeVideo: "",
    institNames: ["University of Michigan - Ann Arbor"],
    title: "1Cademy Node Components",
    nodeImage: "",
    userNodeId: "Tvh7IxaVAGkTATAV9RPT",
    nodeChangeType: "added",
    userNodeChangeType: "added",
    editable: false,
    left: 1350,
    top: 330.5,
    firstVisit: new Date("2023-02-15T20:49:56.817Z"),
    lastVisit: new Date("2023-02-15T20:49:56.817Z"),
    choices: [],
    nodeChanges: null,
    isTag: false,
  },
  "100": {
    ...BASE_NODE,
    node: "100",
    title: "1Cademy",
    content:
      "1Cademy is a collaborative online community that supports interdisciplinary research and learning through content generation, mapping, evaluation, and practice.",
    children: [
      {
        type: "Concept",
        title: "1Cademy Nodes",
        node: "101",
        label: "",
      },
    ],
    parents: [],
  },
  "101": {
    ...BASE_NODE,
    node: "101",
    title: "1Cademy Nodes",
    content:
      "A node is a rectangular box that represents a granular piece of knowledge, summarized in its title and explained in its content.\n\nNodes are connected to other nodes. Together, they make up a hierarchical Knowledge Graph.",
    children: [
      {
        type: "Relation",
        title: "1Cademy Node Components",
        node: "102",
        label: "",
      },
    ],
    parents: [
      {
        node: "100",
        title: "1Cademy",
        type: "Concept",
        label: "",
      },
    ],
    nodeVideo: "https://youtu.be/exLS4UadfFU",
  },
  "102": {
    ...BASE_NODE,
    node: "102",
    title: "1Cademy Node Components",
    content: "Each node in 1Cademy has the following sections: \n- Title \n- Content \n- Header \n- Footer",
    children: [
      {
        type: "Concept",
        title: "1Cademy Node Header",
        node: "103",
        label: "",
      },
    ],
    parents: [
      {
        node: "101",
        title: "1Cademy Nodes",
        type: "Concept",
        label: "",
      },
    ],
    nodeImage:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/UploadedImages%2FK3DmaX1ZAfXSZ5EzWvz46uJ09fZ2%2FSat%2C%2003%20Apr%202021%2000%3A54%3A56%20GMT.png?alt=media&token=c0673481-b22a-4e73-a129-9d0d70841060",
    nodeType: "Relation",
  },
  "103": {
    ...BASE_NODE,
    node: "103",
    title: "1Cademy Node Header",
    content:
      "The header at the top right corner of the node has options to change your view of the map, such as: \n- Collapsing \n- Expanding \n- Hiding \n- Hiding offsprings",
    children: [],
    parents: [
      {
        node: "102",
        title: "1Cademy Node Components",
        type: "Relation",
        label: "",
      },
    ],
    nodeVideo: "https://youtu.be/m6qIjU4tpL4",
  },
};
