const ROUTES = {
  home: "/",
  search: "/search",
  publicHome: "/home",
  assistant: "/assistant",
  node: "/node",
  proposal: "/proposal",
  signIn: "/signin",
  signUp: "/signup",
  signUpExp: "/signinupExp",
  forgotpassword: "/forgot-password",
  notebook: "/notebook",
  instructorsDashboard: "/instructors/dashboard",
  instructorsSettings: "/instructors/settings",
  instructorsSettingsNew: "/instructors/settings#new",
  instructorsStudents: "/instructors/students",
  instructorsDashboardStudents: "/instructors/dashboard/[uname]",
  instructorsNewCourse: "/instructors/course",
  apply: "/#JoinUsSection",
  cookiesPolicy: "/policy/cookies",
  gdprPolicy: "/policy/gdpr",
  privacyPolicy: "/policy/privacy",
  termsPolicy: "/policy/terms",
  studentDashboard: "dashboards",
};

export default ROUTES;
