steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        'docker build -t gcr.io/visualexp-a7d2c/knowledge-dev --build-arg=ONECADEMYCRED_PROJECT_ID="$${ONECADEMYCRED_PROJECT_ID_DEV}" --build-arg=ONECADEMYCRED_PRIVATE_KEY_ID="$${ONECADEMYCRED_PRIVATE_KEY_ID_DEV}" --build-arg=ONECADEMYCRED_PRIVATE_KEY="$${ONECADEMYCRED_PRIVATE_KEY_DEV}" --build-arg=ONECADEMYCRED_CLIENT_EMAIL="$${ONECADEMYCRED_CLIENT_EMAIL_DEV}" --build-arg=ONECADEMYCRED_CLIENT_ID="$${ONECADEMYCRED_CLIENT_ID_DEV}" --build-arg=ONECADEMYCRED_CLIENT_X509_CERT_URL="$${ONECADEMYCRED_CLIENT_X509_CERT_URL_DEV}" --build-arg=NEXT_PUBLIC_API_KEY="$${NEXT_PUBLIC_API_KEY}" --build-arg=NEXT_PUBLIC_MESSAGING_SENDER_ID="$${NEXT_PUBLIC_MESSAGING_SENDER_ID}" --build-arg=NEXT_PUBLIC_APP_ID="$${NEXT_PUBLIC_APP_ID}" --build-arg=NEXT_PUBLIC_STORAGE_BUCKET="$${NEXT_PUBLIC_STORAGE_BUCKET}" --build-arg=NEXT_PUBLIC_PROJECT_ID="$${NEXT_PUBLIC_PROJECT_ID}" --build-arg=NEXT_PUBLIC_DATA_BASE_URL="$${NEXT_PUBLIC_DATA_BASE_URL}" --build-arg=NEXT_PUBLIC_AUTH_DOMAIN="$${NEXT_PUBLIC_AUTH_DOMAIN}" --build-arg=NEXT_PUBLIC_MEASUREMENT_ID="$${NEXT_PUBLIC_MEASUREMENT_ID}" .'
      ]
    env:
      - "NEXT_PUBLIC_AUTH_DOMAIN=${_NEXT_PUBLIC_AUTH_DOMAIN}"
      - "NEXT_PUBLIC_DATA_BASE_URL=${_NEXT_PUBLIC_DATA_BASE_URL}"
      - "NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}"
      - "NEXT_PUBLIC_STORAGE_BUCKET=${_NEXT_PUBLIC_STORAGE_BUCKET}"
    secretEnv:
      [
        "ONECADEMYCRED_PROJECT_ID_DEV",
        "ONECADEMYCRED_CLIENT_EMAIL_DEV",
        "ONECADEMYCRED_CLIENT_ID_DEV",
        "ONECADEMYCRED_CLIENT_X509_CERT_URL_DEV",
        "ONECADEMYCRED_PRIVATE_KEY_DEV",
        "ONECADEMYCRED_PRIVATE_KEY_ID_DEV",
        "NEXT_PUBLIC_API_KEY_DEV",
        "NEXT_PUBLIC_MESSAGING_SENDER_ID_DEV",
        "NEXT_PUBLIC_APP_ID_DEV",
        "NEXT_PUBLIC_MEASUREMENT_ID_DEV"
      ]
  # Push the container image to Container Registry
  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["push", "gcr.io/visualexp-a7d2c/knowledge-dev"]
  # Deploy container image to Cloud Run
  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   entrypoint: gcloud
  #   args:
  #     [
  #       "run",
  #       "deploy",
  #       "knowledge-dev",
  #       "--image",
  #       "gcr.io/visualexp-a7d2c/knowledge-dev",
  #       "--region",
  #       "us-central1",
  #       "--allow-unauthenticated"
  #     ]
images:
  - gcr.io/visualexp-a7d2c/knowledge-dev
availableSecrets:
  secretManager:
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_PROJECT_ID_DEV/versions/1
      env: "ONECADEMYCRED_PROJECT_ID_DEV"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_CLIENT_EMAIL_DEV/versions/1
      env: "ONECADEMYCRED_CLIENT_EMAIL_DEV"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_CLIENT_ID_DEV/versions/1
      env: "ONECADEMYCRED_CLIENT_ID_DEV"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_CLIENT_X509_CERT_URL_DEV/versions/1
      env: "ONECADEMYCRED_CLIENT_X509_CERT_URL_DEV"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_PRIVATE_KEY_DEV/versions/1
      env: "ONECADEMYCRED_PRIVATE_KEY_DEV"
    - versionName: projects/141114383555/secrets/ONECADEMYCRED_PRIVATE_KEY_ID_DEV/versions/1
      env: "ONECADEMYCRED_PRIVATE_KEY_ID_DEV"
    - versionName: projects/141114383555/secrets/NEXT_PUBLIC_API_KEY_DEV/versions/1
      env: "NEXT_PUBLIC_API_KEY_DEV"
    - versionName: projects/141114383555/secrets/NEXT_PUBLIC_MESSAGING_SENDER_ID_DEV/versions/1
      env: "NEXT_PUBLIC_MESSAGING_SENDER_ID_DEV"
    - versionName: projects/141114383555/secrets/NEXT_PUBLIC_APP_ID_DEV/versions/1
      env: "NEXT_PUBLIC_APP_ID_DEV"
    - versionName: projects/141114383555/secrets/NEXT_PUBLIC_MEASUREMENT_ID_DEV/versions/1
      env: "NEXT_PUBLIC_MEASUREMENT_ID_DEV"
timeout: 2000s
