# Step 1. Rebuild the source code only when needed
FROM node:16-alpine AS builder

WORKDIR /app

# Copy lock files if file exists
COPY package.json package-lock.json* ./

# Omit --production flag for TypeScript devDependencies
RUN npm ci --legacy-peer-deps

COPY src ./src
COPY public ./public
COPY next.config.js ./
COPY tsconfig.json ./

# Environment variables must be present at build time
# https://github.com/vercel/next.js/discussions/14030
ARG ONECADEMYCRED_TYPE
ARG ONECADEMYCRED_PRIVATE_KEY_ID
ARG ONECADEMYCRED_PRIVATE_KEY
ARG ONECADEMYCRED_CLIENT_EMAIL
ARG ONECADEMYCRED_CLIENT_ID
ARG ONECADEMYCRED_AUTH_URI
ARG ONECADEMYCRED_TOKEN_URI
ARG ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL
ARG ONECADEMYCRED_CLIENT_X509_CERT_URL
ARG ONECADEMYCRED_TYPESENSE_HOST
ARG ONECADEMYCRED_TYPESENSE_PORT
ARG ONECADEMYCRED_TYPESENSE_PROTOCOL
ARG ONECADEMYCRED_TYPESENSE_APIKEY
ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_AUTH_DOMAIN
ARG NEXT_PUBLIC_DATA_BASE_URL
ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_STORAGE_BUCKET
ARG NEXT_PUBLIC_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_APP_ID
ARG NEXT_PUBLIC_MEASUREMENT_ID
ARG NEXT_PUBLIC_GOOGLE_MAPS_KEY

ENV ONECADEMYCRED_TYPE=${ONECADEMYCRED_TYPE}
ENV ONECADEMYCRED_PRIVATE_KEY_ID=${ONECADEMYCRED_PRIVATE_KEY_ID}
ENV ONECADEMYCRED_PRIVATE_KEY=${ONECADEMYCRED_PRIVATE_KEY}
ENV ONECADEMYCRED_CLIENT_EMAIL=${ONECADEMYCRED_CLIENT_EMAIL}
ENV ONECADEMYCRED_CLIENT_ID=${ONECADEMYCRED_CLIENT_ID}
ENV ONECADEMYCRED_AUTH_URI=${ONECADEMYCRED_AUTH_URI}
ENV ONECADEMYCRED_TOKEN_URI=${ONECADEMYCRED_TOKEN_URI}
ENV ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL=${ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL}
ENV ONECADEMYCRED_CLIENT_X509_CERT_URL=${ONECADEMYCRED_CLIENT_X509_CERT_URL}
ENV ONECADEMYCRED_TYPESENSE_HOST=${ONECADEMYCRED_TYPESENSE_HOST}
ENV ONECADEMYCRED_TYPESENSE_PORT=${ONECADEMYCRED_TYPESENSE_PORT}
ENV ONECADEMYCRED_TYPESENSE_PROTOCOL=${ONECADEMYCRED_TYPESENSE_PROTOCOL}
ENV ONECADEMYCRED_TYPESENSE_APIKEY=${ONECADEMYCRED_TYPESENSE_APIKEY}
ENV NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
ENV NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
ENV NEXT_PUBLIC_DATA_BASE_URL=${NEXT_PUBLIC_DATA_BASE_URL}
ENV NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
ENV NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}
ENV NEXT_PUBLIC_MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID}
ENV NEXT_PUBLIC_MEASUREMENT_ID=${NEXT_PUBLIC_MEASUREMENT_ID}
ENV NEXT_PUBLIC_GOOGLE_MAPS_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_KEY}
ENV NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}

# Uncomment the following line to disable telemetry at build time
# ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

# Step 2. Production image, copy all the files and run next
FROM node:16-alpine AS runner

WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js .
COPY --from=builder /app/package.json .

# Automatically leverage output traces to reduce image size 
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Environment variables must be redefined at run time
ARG ONECADEMYCRED_TYPE
ARG ONECADEMYCRED_PRIVATE_KEY_ID
ARG ONECADEMYCRED_PRIVATE_KEY
ARG ONECADEMYCRED_CLIENT_EMAIL
ARG ONECADEMYCRED_CLIENT_ID
ARG ONECADEMYCRED_AUTH_URI
ARG ONECADEMYCRED_TOKEN_URI
ARG ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL
ARG ONECADEMYCRED_CLIENT_X509_CERT_URL
ARG ONECADEMYCRED_TYPESENSE_HOST
ARG ONECADEMYCRED_TYPESENSE_PORT
ARG ONECADEMYCRED_TYPESENSE_PROTOCOL
ARG ONECADEMYCRED_TYPESENSE_APIKEY
ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_AUTH_DOMAIN
ARG NEXT_PUBLIC_DATA_BASE_URL
ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_STORAGE_BUCKET
ARG NEXT_PUBLIC_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_APP_ID
ARG NEXT_PUBLIC_MEASUREMENT_ID
ARG NEXT_PUBLIC_GOOGLE_MAPS_KEY

ENV ONECADEMYCRED_TYPE=${ONECADEMYCRED_TYPE}
ENV ONECADEMYCRED_PRIVATE_KEY_ID=${ONECADEMYCRED_PRIVATE_KEY_ID}
ENV ONECADEMYCRED_PRIVATE_KEY=${ONECADEMYCRED_PRIVATE_KEY}
ENV ONECADEMYCRED_CLIENT_EMAIL=${ONECADEMYCRED_CLIENT_EMAIL}
ENV ONECADEMYCRED_CLIENT_ID=${ONECADEMYCRED_CLIENT_ID}
ENV ONECADEMYCRED_AUTH_URI=${ONECADEMYCRED_AUTH_URI}
ENV ONECADEMYCRED_TOKEN_URI=${ONECADEMYCRED_TOKEN_URI}
ENV ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL=${ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL}
ENV ONECADEMYCRED_CLIENT_X509_CERT_URL=${ONECADEMYCRED_CLIENT_X509_CERT_URL}
ENV ONECADEMYCRED_TYPESENSE_HOST=${ONECADEMYCRED_TYPESENSE_HOST}
ENV ONECADEMYCRED_TYPESENSE_PORT=${ONECADEMYCRED_TYPESENSE_PORT}
ENV ONECADEMYCRED_TYPESENSE_PROTOCOL=${ONECADEMYCRED_TYPESENSE_PROTOCOL}
ENV ONECADEMYCRED_TYPESENSE_APIKEY=${ONECADEMYCRED_TYPESENSE_APIKEY}
ENV NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
ENV NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
ENV NEXT_PUBLIC_DATA_BASE_URL=${NEXT_PUBLIC_DATA_BASE_URL}
ENV NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
ENV NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}
ENV NEXT_PUBLIC_MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID}
ENV NEXT_PUBLIC_MEASUREMENT_ID=${NEXT_PUBLIC_MEASUREMENT_ID}
ENV NEXT_PUBLIC_GOOGLE_MAPS_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_KEY}

# Uncomment the following line to disable telemetry at run time
# ENV NEXT_TELEMETRY_DISABLED 1

CMD node server.js
