const whyItems = [
  {
    name: "1Cademy AI assistant motivates the development of valuable habits.",
    body: "The 1Cademy AI assistant not only encourages the formation of beneficial habits, but also intelligently recognizes how these habits can improve your life and motivates you to invest more time in them.",
    image: "assistant/1-climing-and-helping-light.svg",
    imageDark: "assistant/1-climing-and-helping-dark.svg",
    padding: "4px 40px 0px 40px",
    width: "auto",
    height: "100%",
  },
  {
    name: "Auto-schedules your tasks.",
    body: "Your assistant checks your existing schedule to optimize time-allocation for your tasks. It also allows you to easily reschedule tasks to different times or days if you are unable to complete them.",
    image: "assistant/2-auto-schedule.svg",
    imageDark: "assistant/2-auto-schedule.svg",
    padding: "4px 40px 0px 40px",
    width: "auto",
    height: "100%",
  },
  {
    name: "Schedules your 1-to-1 and group meetings.",
    body: "Your assistant knows everybody’s schedules and shares a subset of their availability to allow them to easily coordinate meetings. It highly values privacy and does not share the details of everything in users’ schedules.",
    image: "assistant/3-schedules-your-1-to-1-and-group-meetings-light.svg",
    imageDark: "assistant/3-schedules-your-1-to-1-and-group-meetings-dark.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
  {
    name: "Is in sync with your instructors.",
    body: "Your assistant knows the courses you’re taking, your assignment deadlines, classes, and exams. It motivates you to study  and finish your assignments on time. Also, it keeps an eye on your assignment/exam scores and prioritizes your future activities accordingly.",
    image: "assistant/4-is-in-sync-light.svg",
    imageDark: "assistant/4-is-in-sync-dark.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
  {
    name: "An AI Assistant for Free!!!",
    body: "You can use all the capabilities of your AI assistant without paying a penny for as long as you wish. We are a research group at the University of Michigan and Honor Education. \nOur only intentions are to improve human life and education. Our research is done using anonymous data and we do not share your personal data with any third parties.",
    image: "assistant/5-ai-assistant.svg",
    imageDark: "assistant/5-ai-assistant-dark.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
  {
    name: "Schedules tasks and meetings based on you priorities.",
    body: "When scheduling your tasks and meetings, your assistant always keeps an eye on the deadlines and priorities you define for your goals and activities.",
    image: "assistant/6-schedule-task.svg",
    imageDark: "assistant/6-schedule-task-dark.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
  {
    name: "Signals how close you are to each deadline.",
    body: "Your assistant color-codes your tasks/habits based on how close they are to their deadlines. This allows you to quickly depict your progress and assess your available time to finish each task, directly in your Google Calendar.",
    image: "assistant/7-signals-how-close.svg",
    imageDark: "assistant/7-signals-how-close-dark.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
  {
    name: "Motivates through points and badges.",
    body: "Your assistant acknowledges your hard work by rewarding you with badges along the way from completing tasks and keeping up with good habits.",
    image: "assistant/8-motivates-through.svg",
    imageDark: "assistant/8-motivates-through.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
  {
    name: "Allows you to easily modify your schedule.",
    body: "You can easily drag your tasks and events around, directly in your Google Calendar or your Personal Assistant page. \n1Cademy assistant will seamlessly assist you even if you are not in the app. It is aware of the adjustments in your schedule whenever and wherever you change them, so it can adapt your future plans accordingly.",
    image: "assistant/9-allows-you-to-easily-modify.svg",
    imageDark: "assistant/9-allows-you-to-easily-modify.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
  {
    name: "Uses scientifically proven techniques to boost your long-term  learning.",
    body: "Your assistant schedules your studying/practice based on “desirable difficulties.” Desirable difficulties, such as spacing and interleaving, are study/practice scheduling techniques proven to significantly improve long-term learning, in all age and ethnic  groups, genders, and across verbal,  mathematical, motor, visual, and inductive  learning.",
    image: "assistant/10-uses-scientifically-proven.svg",
    imageDark: "assistant/10-uses-scientifically-proven-dark.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
  {
    name: "Leverages methods to mitigate procrastination and reduce burn-out.",
    body: "Pomodoro technique is used in Scrum and Agile management methods. It sets blocks of productive time with short breaks in-between to ensure that productive time is not interrupted but that there is  adequate time off to prevent fatigue or burn-out.",
    image: "assistant/11-leverages-methods.svg",
    imageDark: "assistant/11-leverages-methods-dark.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
  {
    name: "Leverages the psychology of motivation.",
    body: "Prospect theory explains that humans are more sensitive to incremental gains (and losses) compared to the same total value gained (lost) at once. Loss aversion explains that humans are more sensitive to losing than gaining the same value. \n1Cademy assistant helps you break your tasks/habits into small pieces to perceive more success than accomplishing the entire goal at once. It also makes your losses as prominent as your gains to motivate you to learn from your losses.",
    image: "assistant/12-prospect-therory.svg",
    imageDark: "assistant/12-prospect-therory-dark.svg",
    padding: "4px 40px 0px 40px",
    width: "100%",
    height: "auto",
  },
];

export default whyItems;
