import { firstWeekMonthDays } from "../../src/utils";

const { firstWeekDay, firstMonthDay } = firstWeekMonthDays();

const collection = "comMonthlyPoints";

const data: any[] = [
  {
    documentId: "2Zb5dE2cDZqWpg1ldMbO",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstMonthDay,
    aChooseUname: false,
    aFullname: "Iman YeckehZaare",
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Fa2m8BaOOO2OrIhKGIOmz7Ly1v8q1%2FWed%2C%2009%20Dec%202020%2002%3A37%3A12%20GMT.jpg?alt=media&token=db5b7e1b-8545-4cb7-b3ee-c5d37ed62ac0",
    admin: "1man",
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    tag: "1Cademy",
    lterm: 0.0,
    ltermDay: 0,
    cnCorrects: 0.0,
    cnInst: 0.0,
    cdCorrects: 0.0,
    cdInst: 0.0,
    qCorrects: 0.0,
    qInst: 0.0,
    pCorrects: 0.0,
    pInst: 0.0,
    sCorrects: 0.0,
    sInst: 0.0,
    aCorrects: 0.0,
    aInst: 0.0,
    rfCorrects: 0.0,
    rfInst: 0.0,
    nCorrects: 0.0,
    nInst: 0.0,
    iCorrects: 0.0,
    iInst: 0.0,
    mCorrects: 0.0,
    mInst: 0.0,
    cnWrongs: 0.0,
    cdWrongs: 0.0,
    qWrongs: 0.0,
    pWrongs: 0.0,
    sWrongs: 0.0,
    aWrongs: 0.0,
    rfWrongs: 0.0,
    nWrongs: 0.0,
    iWrongs: 0.0,
    mWrongs: 0.0,
    negatives: 0.0,
    positives: 0.0,
    totalPoints: 0.0,
  },
  {
    documentId: "2Zb5dE2cDZqWpg1ldNvO",
    nCorrects: 0,
    aInst: 0,
    pInst: 0,
    aCorrects: 0,
    cdCorrects: 0,
    rfInst: 0,
    ltermDay: 0,
    iInst: 0,
    mWrongs: 0,
    nWrongs: 0,
    tag: "1Cademy",
    adminPoints: 0,
    iCorrects: 0,
    rfCorrects: 0,
    iWrongs: 0,
    aWrongs: 0,
    cnInst: 0,
    createdAt: new Date(),
    tagId: "FJfzAX7zbgQS8jU5XcEk",
    updatedAt: new Date(),
    firstWeekDay,
    firstMonthDay,
    qCorrects: 0,
    lterm: 0,
    cnWrongs: 0,
    sCorrects: 0,
    sWrongs: 0,
    mInst: 0,
    sInst: 0,
    aChooseUname: false,
    qWrongs: 0,
    aFullname: "1man",
    cdInst: 0,
    rfWrongs: 0,
    cnCorrects: 0,
    pCorrects: 0,
    mCorrects: 0,
    cdWrongs: 0,
    totalPoints: 0,
    aImgUrl: null,
    qInst: 0,
    pWrongs: 0,
    nInst: 0,
    positives: 0,
    negatives: 0,
  },
  {
    documentId: "Nokz3iyYE0",
    nCorrects: 0,
    aInst: 0,
    pInst: 0,
    aCorrects: 0,
    cdCorrects: 0,
    rfInst: 0,
    ltermDay: 0,
    iInst: 0,
    mWrongs: 0,
    nWrongs: 0,
    tag: "1Cademy",
    adminPoints: 0,
    iCorrects: 0,
    rfCorrects: 0,
    iWrongs: 0,
    aWrongs: 0,
    cnInst: 0,
    createdAt: new Date(),
    tagId: "C7L3gNbNp5reFjQf8vAb",
    updatedAt: new Date(),
    firstWeekDay,
    firstMonthDay,
    qCorrects: 0,
    lterm: 0,
    cnWrongs: 0,
    sCorrects: 0,
    sWrongs: 0,
    mInst: 0,
    sInst: 0,
    aChooseUname: false,
    qWrongs: 0,
    aFullname: "Alvin Wei",
    admin: "A_wei",
    cdInst: 0,
    rfWrongs: 0,
    cnCorrects: 0,
    pCorrects: 0,
    mCorrects: 0,
    cdWrongs: 0,
    totalPoints: 0,
    aImgUrl: null,
    qInst: 0,
    pWrongs: 0,
    nInst: 0,
    positives: 0,
    negatives: 0,
  },
];

const comMonthlyPointsData = {
  data,
  collection,
};

export default comMonthlyPointsData;
