const collection = "comOthMonPoints";

const data: any[] = [
  {
    documentId: "2rV4j4bQUjoW3JZ7It6X",
    pWrongs: 0,
    ltermDay: 0,
    mWrongs: 0,
    qWrongs: 0,
    createdAt: new Date(),
    aChooseUname: false,
    tag: "1Cademy",
    mCorrects: 0,
    cdWrongs: 0,
    positives: 1,
    totalPoints: 1,
    qInst: 0,
    nInst: 0,
    nCorrects: 0,
    cnInst: 0,
    qCorrects: 0,
    iCorrects: 0,
    rfInst: 0,
    sWrongs: 0,
    cnWrongs: 0,
    negatives: 0,
    aInst: 0,
    aFullname: "David Sohn",
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    iInst: 0,
    aCorrects: 0,
    sInst: 0,
    rfWrongs: 0,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FAEeN67xP5cUpwxYUIUA0ZnUuaHw2%2FFri%2C%2026%20Jun%202020%2019%3A57%3A11%20GMT.jpg?alt=media&token=8a2aa859-d5f3-4ecd-8d5f-85f409bc7260",
    cnCorrects: 1,
    adminPoints: 1,
    rfCorrects: 0,
    lterm: 0,
    nWrongs: 0,
    cdCorrects: 0,
    pInst: 0,
    aWrongs: 0,
    iWrongs: 0,
    pCorrects: 0,
    sCorrects: 0,
    cdInst: 0,
    mInst: 0,
    updatedAt: new Date(),
    admin: "dsohn",
  },
];
const comOthMonPointsData = {
  data,
  collection,
};

export default comOthMonPointsData;
