const collection = "comOthWeekPoints";

const data: any[] = [
  {
    documentId: "939oRTjRcQT7mKyfLbuc",
    cnInst: 0,
    aFullname: null,
    mWrongs: 0,
    rfWrongs: 0,
    aWrongs: 0,
    pWrongs: 0,
    aCorrects: 0,
    aInst: 0,
    nInst: 0,
    rfInst: 0,
    positives: 4,
    mCorrects: 0,
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    nCorrects: 0,
    totalPoints: 4,
    sCorrects: 0,
    aChooseUname: false,
    iWrongs: 0,
    createdAt: new Date(),
    sInst: 0,
    mInst: 0,
    qWrongs: 0,
    cdWrongs: 0,
    cnWrongs: 0,
    pInst: 0,
    rfCorrects: 0,
    sWrongs: 0,
    adminPoints: 1,
    nWrongs: 0,
    cnCorrects: 4,
    ltermDay: 0,
    pCorrects: 0,
    cdCorrects: 0,
    aImgUrl: null,
    qInst: 0,
    iCorrects: 0,
    updatedAt: new Date(),
    negatives: 0,
    iInst: 0,
    lterm: 0,
    cdInst: 0,
    tag: "1Cademy",
    qCorrects: 0,
  },
];

const comOthWeekPointsData = {
  data,
  collection,
};

export default comOthWeekPointsData;
