const collection = "comOthersPoints";

const data: any[] = [
  {
    documentId: "5evtajKZPozXAqjjtH0D",
    createdAt: new Date(),
    updatedAt: new Date(),
    aChooseUname: false,
    aFullname: "Iman YeckehZaare",
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Fa2m8BaOOO2OrIhKGIOmz7Ly1v8q1%2FWed%2C%2009%20Dec%202020%2002%3A37%3A12%20GMT.jpg?alt=media&token=db5b7e1b-8545-4cb7-b3ee-c5d37ed62ac0",
    admin: "1man",
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    tag: "1Cademy",
    lterm: 0.0,
    ltermDay: 0,
    cnCorrects: 0.0,
    cnInst: 0.0,
    cdCorrects: 0.0,
    cdInst: 0.0,
    qCorrects: 0.0,
    qInst: 0.0,
    pCorrects: 0.0,
    pInst: 0.0,
    sCorrects: 0.0,
    sInst: 0.0,
    aCorrects: 0.0,
    aInst: 0.0,
    rfCorrects: 0.0,
    rfInst: 0.0,
    nCorrects: 0.0,
    nInst: 0.0,
    iCorrects: 0.0,
    iInst: 0.0,
    mCorrects: 0.0,
    mInst: 0.0,
    cnWrongs: 0.0,
    cdWrongs: 0.0,
    qWrongs: 0.0,
    pWrongs: 0.0,
    sWrongs: 0.0,
    aWrongs: 0.0,
    rfWrongs: 0.0,
    nWrongs: 0.0,
    iWrongs: 0.0,
    mWrongs: 0.0,
    negatives: 0.0,
    positives: 0.0,
    totalPoints: 0.0,
  },
  {
    documentId: "5evtazGZPozXAqjjtH0D",
    negatives: null,
    sInst: null,
    mInst: 0,
    totalPoints: null,
    cnInst: null,
    aFullname: "Gail Grot",
    lterm: 0,
    pInst: null,
    mCorrects: 1399.87,
    qInst: null,
    ltermDay: 0,
    rfCorrects: null,
    pCorrects: null,
    admin: "Grae",
    iCorrects: 100.5,
    nWrongs: null,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Fa2m8BaOOO2OrIhKGIOmz7Ly1v8q1%2FWed%2C%2009%20Dec%202020%2002%3A37%3A12%20GMT.jpg?alt=media&token=db5b7e1b-8545-4cb7-b3ee-c5d37ed62ac0",
    cdCorrects: null,
    aWrongs: null,
    nCorrects: null,
    aChooseUname: false,
    iWrongs: 38.01,
    adminPoints: 215.02,
    aCorrects: null,
    cdInst: null,
    rfInst: null,
    sCorrects: null,
    nInst: null,
    pWrongs: null,
    mWrongs: 198.44,
    aInst: null,
    cdWrongs: null,
    qCorrects: null,
    createdAt: new Date(),
    positives: null,
    cnCorrects: null,
    qWrongs: null,
    rfWrongs: null,
    sWrongs: null,
    cnWrongs: null,
    updatedAt: new Date(),
    iInst: 0,
    tag: "1Cademy",
    tagId: "FJfzAX7zbgQS8jU5XcEk",
  },

  {
    documentId: "WymXT8Zu8C",
    aCorrects: 0,
    lterm: 0,
    iInst: 0,
    rfCorrects: 0,
    createdAt: new Date(),
    qCorrects: 0,
    pCorrects: 0,
    nCorrects: 0,
    totalPoints: 345.58,
    aWrongs: 0,
    mInst: 0,
    qWrongs: 0,
    iCorrects: 0,
    adminPoints: 52,
    positives: 388.89,
    cnInst: 0,
    ltermDay: 0,
    updatedAt: new Date(),
    cnCorrects: 0,
    mCorrects: 187.31,
    aImgUrl: "https://storage.googleapis.com/onecademy-1.appspot.com/ProfilePictures/no-img.png",
    sInst: 0,
    pInst: 0,
    admin: "A_wei",
    cnWrongs: 0,
    aFullname: "Alvin Wei",
    iWrongs: 0,
    tag: "SARS-CoV-2 (COVID-19)",
    qInst: 0,
    rfInst: 0,
    rfWrongs: 0,
    cdWrongs: 0,
    negatives: 43.31,
    nWrongs: 0,
    nInst: 0,
    aInst: 0,
    pWrongs: 0,
    sCorrects: 0,
    mWrongs: 62.01,
    cdInst: 0,
    cdCorrects: 0,
    sWrongs: 0,
    tagId: "uYgvhNdciHcuK7ioGZEv",
  },
  {
    documentId: "WymXT9Yu4C",
    aCorrects: 0,
    lterm: 0,
    iInst: 0,
    rfCorrects: 0,
    createdAt: new Date(),
    qCorrects: 0,
    pCorrects: 0,
    nCorrects: 0,
    totalPoints: 345.58,
    aWrongs: 0,
    mInst: 0,
    qWrongs: 0,
    iCorrects: 0,
    adminPoints: 52,
    positives: 388.89,
    cnInst: 0,
    ltermDay: 0,
    updatedAt: new Date(),
    cnCorrects: 0,
    mCorrects: 187.31,
    aImgUrl: "https://storage.googleapis.com/onecademy-1.appspot.com/ProfilePictures/no-img.png",
    sInst: 0,
    pInst: 0,
    admin: "A_wei",
    cnWrongs: 0,
    aFullname: "Alvin Wei",
    iWrongs: 0,
    tag: "SARS-CoV-2 (COVID-19)",
    qInst: 0,
    rfInst: 0,
    rfWrongs: 0,
    cdWrongs: 0,
    negatives: 43.31,
    nWrongs: 0,
    nInst: 0,
    aInst: 0,
    pWrongs: 0,
    sCorrects: 0,
    mWrongs: 62.01,
    cdInst: 0,
    cdCorrects: 0,
    sWrongs: 0,
    tagId: "kAyHgnb1ou6YNfv36K6a",
  },
];

const comOthersPointsData = {
  data,
  collection,
};

export default comOthersPointsData;
