const collection = "comOthWeekPoints";

const data: any[] = [
  {
    documentId: "939oRTjRcQT7mKyfLbuc",
    cnInst: 0,
    aFullname: null,
    mWrongs: 0,
    rfWrongs: 0,
    aWrongs: 0,
    pWrongs: 0,
    aCorrects: 0,
    aInst: 0,
    nInst: 0,
    rfInst: 0,
    positives: 4,
    mCorrects: 0,
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    nCorrects: 0,
    totalPoints: 4,
    sCorrects: 0,
    aChooseUname: false,
    iWrongs: 0,
    createdAt: new Date(),
    sInst: 0,
    mInst: 0,
    qWrongs: 0,
    cdWrongs: 0,
    cnWrongs: 0,
    pInst: 0,
    rfCorrects: 0,
    sWrongs: 0,
    adminPoints: 1,
    nWrongs: 0,
    cnCorrects: 4,
    ltermDay: 0,
    pCorrects: 0,
    cdCorrects: 0,
    aImgUrl: null,
    qInst: 0,
    iCorrects: 0,
    updatedAt: new Date(),
    negatives: 0,
    iInst: 0,
    lterm: 0,
    cdInst: 0,
    tag: "1Cademy",
    qCorrects: 0,
  },
  {
    documentId: "tHjhYwTHo6",
    tag: "Biomedical Sciences",
    cnWrongs: 0,
    sWrongs: 0,
    negatives: 0,
    mCorrects: 8,
    sCorrects: 0,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FbofdYnPC8EU7nkxM6x9NjSQq6UQ2%2FTue%2C%2030%20Jun%202020%2020%3A22%3A05%20GMT.jpeg?alt=media&token=49ec9a76-e84b-4583-9685-a9e22a5d25a6",
    cdWrongs: 0,
    mWrongs: 0,
    qWrongs: 0,
    pInst: 0,
    iWrongs: 0,
    tagId: "JvMjw4kbgeqNA7sRQjfZ",
    nCorrects: 0,
    ltermDay: 0,
    cdInst: 0,
    iCorrects: 0,
    sInst: 0,
    mInst: 0,
    lterm: 0,
    positives: 8,
    aChooseUname: false,
    rfInst: 0,
    aCorrects: 0,
    pCorrects: 0,
    adminPoints: 3,
    rfWrongs: 0,
    nWrongs: 0,
    cnInst: 0,
    iInst: 0,
    aFullname: "Alvin Wei",
    pWrongs: 0,
    firstWeekDay: "9-4-2022",
    qInst: 0,
    nInst: 0,
    rfCorrects: 0,
    aWrongs: 0,
    admin: "A_wei",
    cnCorrects: 0,
    updatedAt: new Date(),
    totalPoints: 8,
    qCorrects: 0,
    aInst: 0,
    createdAt: new Date(),
    cdCorrects: 0,
  },
];

const comOthWeekPointsData = {
  data,
  collection,
};

export default comOthWeekPointsData;
