const collection = "comPoints";

const data: any[] = [
  {
    documentId: "YLTLdwaktLcPihjuwMc8",
    createdAt: new Date(),
    updatedAt: new Date(),
    aChooseUname: false,
    aFullname: "Iman YeckehZaare",
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Fa2m8BaOOO2OrIhKGIOmz7Ly1v8q1%2FWed%2C%2009%20Dec%202020%2002%3A37%3A12%20GMT.jpg?alt=media&token=db5b7e1b-8545-4cb7-b3ee-c5d37ed62ac0",
    admin: "1man",
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    tag: "1Cademy",
    lterm: 0.0,
    ltermDay: 0,
    cnCorrects: 0.0,
    cnInst: 0.0,
    cdCorrects: 0.0,
    cdInst: 0.0,
    qCorrects: 0.0,
    qInst: 0.0,
    pCorrects: 0.0,
    pInst: 0.0,
    sCorrects: 0.0,
    sInst: 0.0,
    aCorrects: 0.0,
    aInst: 0.0,
    rfCorrects: 0.0,
    rfInst: 0.0,
    nCorrects: 0.0,
    nInst: 0.0,
    iCorrects: 0.0,
    iInst: 0.0,
    mCorrects: 0.0,
    mInst: 0.0,
    cnWrongs: 0.0,
    cdWrongs: 0.0,
    qWrongs: 0.0,
    pWrongs: 0.0,
    sWrongs: 0.0,
    aWrongs: 0.0,
    rfWrongs: 0.0,
    nWrongs: 0.0,
    iWrongs: 0.0,
    mWrongs: 0.0,
    negatives: 0.0,
    positives: 0.0,
    totalPoints: 0.0,
  },
  {
    documentId: "YLTLdwaktLcPihF3wMc8",
    createdAt: new Date(),
    rfWrongs: null,
    cdWrongs: null,
    adminPoints: 457,
    qCorrects: null,
    iInst: 0,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Ffe3S7b03HRRRbEW4q4uMhOswFFk1%2FTue%2C%2027%20Jul%202021%2013%3A52%3A05%20GMT.jpg?alt=media&token=f0099650-c7ad-4743-a762-e99527a7a02f",
    pCorrects: null,
    nCorrects: null,
    sInst: null,
    nInst: null,
    rfInst: null,
    iCorrects: 0,
    sCorrects: null,
    ltermDay: 0,
    aWrongs: null,
    mWrongs: 32.5,
    cdCorrects: null,
    tag: "1Cademy",
    aCorrects: null,
    nWrongs: null,
    qWrongs: null,
    sWrongs: null,
    rfCorrects: null,
    cnWrongs: null,
    mCorrects: 454.5,
    cnCorrects: null,
    totalPoints: 1888.71,
    cdInst: null,
    aInst: null,
    aFullname: "Ysabelle Broderson",
    qInst: null,
    negatives: 174.55,
    lterm: 0,
    admin: "ybroderson",
    tagId: "FJfzAX7zbgQS8jU5XcEk",
    positives: 2063.26,
    iWrongs: 0,
    pWrongs: null,
    updatedAt: new Date(),
    pInst: null,
    cnInst: null,
    mInst: 0,
  },
  {
    documentId: "khsqamXO9a",
    createdAt: new Date(),
    rfWrongs: null,
    cdWrongs: null,
    adminPoints: 457,
    qCorrects: null,
    iInst: 0,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Ffe3S7b03HRRRbEW4q4uMhOswFFk1%2FTue%2C%2027%20Jul%202021%2013%3A52%3A05%20GMT.jpg?alt=media&token=f0099650-c7ad-4743-a762-e99527a7a02f",
    pCorrects: null,
    nCorrects: null,
    sInst: null,
    nInst: null,
    rfInst: null,
    iCorrects: 0,
    sCorrects: null,
    ltermDay: 0,
    aWrongs: null,
    mWrongs: 32.5,
    cdCorrects: null,
    tag: "1Cademy",
    aCorrects: null,
    nWrongs: null,
    qWrongs: null,
    sWrongs: null,
    rfCorrects: null,
    cnWrongs: null,
    mCorrects: 454.5,
    cnCorrects: null,
    totalPoints: 1888.71,
    cdInst: null,
    aInst: null,
    aFullname: "Ysabelle Broderson",
    qInst: null,
    negatives: 174.55,
    lterm: 0,
    admin: "A_wei",
    tagId: "FJfzAX7zbgQS8jU5XcEk",
    positives: 2063.26,
    iWrongs: 0,
    pWrongs: null,
    updatedAt: new Date(),
    pInst: null,
    cnInst: null,
    mInst: 0,
  },
];

const comPintsData = {
  data,
  collection,
};

export default comPintsData;
