const collection = "comPoints";

const data: any[] = [
  {
    documentId: "YLTLdwaktLcPihjuwMc8",
    createdAt: new Date(),
    rfWrongs: null,
    cdWrongs: null,
    adminPoints: 457,
    qCorrects: null,
    iInst: 0,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Ffe3S7b03HRRRbEW4q4uMhOswFFk1%2FTue%2C%2027%20Jul%202021%2013%3A52%3A05%20GMT.jpg?alt=media&token=f0099650-c7ad-4743-a762-e99527a7a02f",
    pCorrects: null,
    nCorrects: null,
    sInst: null,
    nInst: null,
    rfInst: null,
    iCorrects: 0,
    sCorrects: null,
    ltermDay: 0,
    aWrongs: null,
    mWrongs: 32.5,
    cdCorrects: null,
    tag: "1Cademy",
    aCorrects: null,
    nWrongs: null,
    qWrongs: null,
    sWrongs: null,
    rfCorrects: null,
    cnWrongs: null,
    mCorrects: 454.5,
    cnCorrects: null,
    totalPoints: 1888.71,
    cdInst: null,
    aInst: null,
    aFullname: "Ysabelle Broderson",
    qInst: null,
    negatives: 174.55,
    lterm: 0,
    admin: "ybroderson",
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    positives: 2063.26,
    iWrongs: 0,
    pWrongs: null,
    updatedAt: new Date(),
    pInst: null,
    cnInst: null,
    mInst: 0,
  },
  {
    documentId: "YLTLdwaktLcPihF3wMc8",
    createdAt: new Date(),
    rfWrongs: null,
    cdWrongs: null,
    adminPoints: 457,
    qCorrects: null,
    iInst: 0,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Ffe3S7b03HRRRbEW4q4uMhOswFFk1%2FTue%2C%2027%20Jul%202021%2013%3A52%3A05%20GMT.jpg?alt=media&token=f0099650-c7ad-4743-a762-e99527a7a02f",
    pCorrects: null,
    nCorrects: null,
    sInst: null,
    nInst: null,
    rfInst: null,
    iCorrects: 0,
    sCorrects: null,
    ltermDay: 0,
    aWrongs: null,
    mWrongs: 32.5,
    cdCorrects: null,
    tag: "1Cademy",
    aCorrects: null,
    nWrongs: null,
    qWrongs: null,
    sWrongs: null,
    rfCorrects: null,
    cnWrongs: null,
    mCorrects: 454.5,
    cnCorrects: null,
    totalPoints: 1888.71,
    cdInst: null,
    aInst: null,
    aFullname: "Ysabelle Broderson",
    qInst: null,
    negatives: 174.55,
    lterm: 0,
    admin: "ybroderson",
    tagId: "FJfzAX7zbgQS8jU5XcEk",
    positives: 2063.26,
    iWrongs: 0,
    pWrongs: null,
    updatedAt: new Date(),
    pInst: null,
    cnInst: null,
    mInst: 0,
  },
  {
    documentId: "khsqamXO9a",
    createdAt: new Date(),
    rfWrongs: null,
    cdWrongs: null,
    adminPoints: 457,
    qCorrects: null,
    iInst: 0,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Ffe3S7b03HRRRbEW4q4uMhOswFFk1%2FTue%2C%2027%20Jul%202021%2013%3A52%3A05%20GMT.jpg?alt=media&token=f0099650-c7ad-4743-a762-e99527a7a02f",
    pCorrects: null,
    nCorrects: null,
    sInst: null,
    nInst: null,
    rfInst: null,
    iCorrects: 0,
    sCorrects: null,
    ltermDay: 0,
    aWrongs: null,
    mWrongs: 32.5,
    cdCorrects: null,
    tag: "1Cademy",
    aCorrects: null,
    nWrongs: null,
    qWrongs: null,
    sWrongs: null,
    rfCorrects: null,
    cnWrongs: null,
    mCorrects: 454.5,
    cnCorrects: null,
    totalPoints: 1888.71,
    cdInst: null,
    aInst: null,
    aFullname: "Ysabelle Broderson",
    qInst: null,
    negatives: 174.55,
    lterm: 0,
    admin: "A_wei",
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    positives: 2063.26,
    iWrongs: 0,
    pWrongs: null,
    updatedAt: new Date(),
    pInst: null,
    cnInst: null,
    mInst: 0,
  },
];

const comPintsData = {
  data,
  collection,
};

export default comPintsData;
