const collection = "comWeeklyPoints";

const data: any[] = [
  {
    documentId: "Brit3GCGzeFOvXRq55vV",
    sInst: 0,
    totalPoints: 6,
    aCorrects: 0,
    nInst: 0,
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    mInst: 0,
    cdInst: 0,
    positives: 6,
    rfInst: 0,
    sCorrects: 0,
    nWrongs: 0,
    pWrongs: 0,
    adminPoints: 1,
    lterm: 0,
    cdCorrects: 0,
    qWrongs: 0,
    tag: "1Cademy",
    aChooseUname: false,
    rfWrongs: 0,
    mCorrects: 0,
    aImgUrl: null,
    cdWrongs: 0,
    qCorrects: 0,
    iInst: 0,
    updatedAt: new Date(),
    cnInst: 0,
    qInst: 0,
    aWrongs: 0,
    ltermDay: 0,
    mWrongs: 0,
    aInst: 0,
    iWrongs: 0,
    negatives: 0,
    sWrongs: 0,
    aFullname: null,
    pCorrects: 0,
    nCorrects: 0,
    createdAt: new Date(),
    cnWrongs: 0,
    rfCorrects: 0,
    iCorrects: 0,
    pInst: 0,
    cnCorrects: 6,
  },
  {
    rfInst: 0,
    tag: "Biomedical Sciences",
    cnInst: 0,
    aInst: 0,
    positives: 1,
    pCorrects: 0,
    sCorrects: 0,
    mInst: 0,
    cdInst: 0,
    admin: "A_wei",
    adminPoints: 1,
    updatedAt: new Date(),
    aCorrects: 0,
    mCorrects: 0,
    mWrongs: 0,
    qCorrects: 0,
    qWrongs: 0,
    ltermDay: 0,
    lterm: 0,
    nWrongs: 0,
    cnCorrects: 1,
    aFullname: "Alvin Wei",
    rfWrongs: 0,
    pInst: 0,
    iWrongs: 0,
    createdAt: new Date(),
    iInst: 0,
    nInst: 0,
    qInst: 0,
    cnWrongs: 0,
    sWrongs: 0,
    sInst: 0,
    tagId: "JvMjw4kbgeqNA7sRQjfZ",
    aChooseUname: false,
    rfCorrects: 0,
    iCorrects: 0,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2F4s7IgZhT5zYZ7AyWKDXQVCFZv3y1%2FMon%2C%2004%20Jan%202021%2001%3A26%3A34%20GMT.jpg?alt=media&token=a375d2fc-3b72-4658-80ea-69b346e79596",
    pWrongs: 0,
    cdWrongs: 0,
    totalPoints: 1,
    negatives: 0,
    aWrongs: 0,
    nCorrects: 0,
    cdCorrects: 0,
  },
];

const comWeeklyPointsData = {
  data,
  collection,
};

export default comWeeklyPointsData;
