import { firstWeekMonthDays } from "../../src/utils";

const { firstWeekDay } = firstWeekMonthDays();

const collection = "comWeeklyPoints";

const data: any[] = [
  {
    documentId: "Brit3GCGzeFOvXRq55vV",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstWeekDay,
    aChooseUname: false,
    aFullname: "Iman YeckehZaare",
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2Fa2m8BaOOO2OrIhKGIOmz7Ly1v8q1%2FWed%2C%2009%20Dec%202020%2002%3A37%3A12%20GMT.jpg?alt=media&token=db5b7e1b-8545-4cb7-b3ee-c5d37ed62ac0",
    admin: "1man",
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    tag: "1Cademy",
    lterm: 0.0,
    ltermDay: 0,
    cnCorrects: 0.0,
    cnInst: 0.0,
    cdCorrects: 0.0,
    cdInst: 0.0,
    qCorrects: 0.0,
    qInst: 0.0,
    pCorrects: 0.0,
    pInst: 0.0,
    sCorrects: 0.0,
    sInst: 0.0,
    aCorrects: 0.0,
    aInst: 0.0,
    rfCorrects: 0.0,
    rfInst: 0.0,
    nCorrects: 0.0,
    nInst: 0.0,
    iCorrects: 0.0,
    iInst: 0.0,
    mCorrects: 0.0,
    mInst: 0.0,
    cnWrongs: 0.0,
    cdWrongs: 0.0,
    qWrongs: 0.0,
    pWrongs: 0.0,
    sWrongs: 0.0,
    aWrongs: 0.0,
    rfWrongs: 0.0,
    nWrongs: 0.0,
    iWrongs: 0.0,
    mWrongs: 0.0,
    negatives: 0.0,
    positives: 0.0,
    totalPoints: 0.0,
  },
  {
    rfInst: 0,
    tag: "Biomedical Sciences",
    cnInst: 0,
    aInst: 0,
    positives: 1,
    pCorrects: 0,
    sCorrects: 0,
    mInst: 0,
    cdInst: 0,
    admin: "A_wei",
    adminPoints: 1,
    updatedAt: new Date(),
    aCorrects: 0,
    mCorrects: 0,
    mWrongs: 0,
    qCorrects: 0,
    qWrongs: 0,
    ltermDay: 0,
    lterm: 0,
    nWrongs: 0,
    cnCorrects: 1,
    aFullname: "Alvin Wei",
    rfWrongs: 0,
    pInst: 0,
    iWrongs: 0,
    createdAt: new Date(),
    iInst: 0,
    nInst: 0,
    qInst: 0,
    cnWrongs: 0,
    sWrongs: 0,
    sInst: 0,
    tagId: "JvMjw4kbgeqNA7sRQjfZ",
    aChooseUname: false,
    rfCorrects: 0,
    iCorrects: 0,
    aImgUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2F4s7IgZhT5zYZ7AyWKDXQVCFZv3y1%2FMon%2C%2004%20Jan%202021%2001%3A26%3A34%20GMT.jpg?alt=media&token=a375d2fc-3b72-4658-80ea-69b346e79596",
    pWrongs: 0,
    cdWrongs: 0,
    totalPoints: 1,
    negatives: 0,
    aWrongs: 0,
    nCorrects: 0,
    cdCorrects: 0,
  },
];

const comWeeklyPointsData = {
  data,
  collection,
};

export default comWeeklyPointsData;
