const collection = "conceptVersions";

const data: any[] = [
  {
    documentId: "hZKNPML1D4FzV6etT6ZH",
    tags: ["Data Science"],
    wrongs: 0,
    node: "VnXTRolBGyHF3q8EvxS3",
    proposal: "",
    referenceLabels: [],
    updatedAt: new Date(),
    accepted: true,
    tagIds: ["iUex43wFn3yzFcDbma04"],
    children: [],
    corrects: 1,
    chooseUname: false,
    deleted: false,
    newChild: true,
    content: "https://arxiv.org/pdf/1311.2901.pdf",
    nodeImage: "",
    proposer: "1man",
    summary: "",
    references: [],
    viewers: 1,
    createdAt: new Date(),
    title: "Visualizing and Understanding Convolutional Networks Paper",
    referenceIds: [],
    fullname: "Conner Stevons",
    childType: "Reference",
    parents: [
      {
        label: "",
        node: "OR8UsmsxmeExHG8ekkIY",
        title: "Convolutional Neural Network (CNN)",
      },
    ],
    awards: 0,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FdnSwPNX4gyZN5iQFd9fHBBgnwN82%2FFri%2C%2005%20Feb%202021%2016%3A17%3A04%20GMT.jpg?alt=media&token=fa33055d-5377-4686-87b5-fbf3f8e9dfba",
  },
  {
    documentId: "yJcyNtONmxYQ0R8GBmya",
    tags: ["Data Science"],
    wrongs: 0,
    node: "iUex43wFn3yzFcDbma04",
    proposal: "",
    referenceLabels: [],
    updatedAt: new Date(),
    accepted: true,
    tagIds: ["iUex43wFn3yzFcDbma04"],
    children: [],
    corrects: 1,
    chooseUname: false,
    deleted: false,
    newChild: true,
    content: "https://arxiv.org/pdf/1311.2901.pdf",
    nodeImage: "",
    proposer: "1man",
    summary: "",
    references: [],
    viewers: 1,
    createdAt: new Date(),
    title: "Visualizing and Understanding Convolutional Networks Paper",
    referenceIds: [],
    fullname: "Conner Stevons",
    childType: "Reference",
    parents: [
      {
        label: "",
        node: "OR8UsmsxmeExHG8ekkIY",
        title: "Convolutional Neural Network (CNN)",
      },
    ],
    awards: 0,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FdnSwPNX4gyZN5iQFd9fHBBgnwN82%2FFri%2C%2005%20Feb%202021%2016%3A17%3A04%20GMT.jpg?alt=media&token=fa33055d-5377-4686-87b5-fbf3f8e9dfba",
  },
  {
    documentId: "bbNXGhDXhItVCgbHUcee",
    tags: ["Data Science"],
    wrongs: 0,
    node: "9BVhNniLS940DBVqKbFR",
    proposal: "",
    referenceLabels: [],
    updatedAt: new Date(),
    accepted: true,
    tagIds: ["kAyHgnb1ou6YNfv36K6a"],
    children: [],
    corrects: 1,
    chooseUname: false,
    deleted: false,
    newChild: true,
    content: "https://arxiv.org/pdf/1311.2901.pdf",
    nodeImage: "",
    proposer: "1man",
    summary: "",
    references: [],
    viewers: 1,
    createdAt: new Date(),
    title: "Visualizing and Understanding Convolutional Networks Paper",
    referenceIds: [],
    fullname: "Conner Stevons",
    childType: "Reference",
    parents: [
      {
        label: "",
        node: "OR8UsmsxmeExHG8ekkIY",
        title: "Convolutional Neural Network (CNN)",
      },
    ],
    awards: 0,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FdnSwPNX4gyZN5iQFd9fHBBgnwN82%2FFri%2C%2005%20Feb%202021%2016%3A17%3A04%20GMT.jpg?alt=media&token=fa33055d-5377-4686-87b5-fbf3f8e9dfba",
  },
  {
    documentId: "bkYvkniwziO1Ue6K1gtN",
    tags: ["Data Science"],
    wrongs: 0,
    node: "GJfzAY1zbgQs9jU5XeEL",
    proposal: "",
    referenceLabels: [],
    updatedAt: new Date(),
    accepted: true,
    tagIds: ["GJfzAY1zbgQs9jU5XeEL"],
    children: [],
    corrects: 1,
    chooseUname: false,
    deleted: false,
    newChild: true,
    content: "https://arxiv.org/pdf/1311.2901.pdf",
    nodeImage: "",
    proposer: "A_wei",
    summary: "",
    references: [],
    viewers: 1,
    createdAt: new Date(),
    title: "Visualizing and Understanding Convolutional Networks Paper",
    referenceIds: [],
    fullname: "Conner Stevons",
    childType: "Reference",
    parents: [
      {
        label: "",
        node: "OR8UsmsxmeExHG8ekkIY",
        title: "Convolutional Neural Network (CNN)",
      },
    ],
    awards: 0,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FdnSwPNX4gyZN5iQFd9fHBBgnwN82%2FFri%2C%2005%20Feb%202021%2016%3A17%3A04%20GMT.jpg?alt=media&token=fa33055d-5377-4686-87b5-fbf3f8e9dfba",
  },
  {
    documentId: "bkZvkniwziO1Ue7K9gtX",
    tags: ["Data Science"],
    wrongs: 0,
    node: "OR8UsmsxmeExHG8ekkIY",
    proposal: "",
    referenceLabels: [],
    updatedAt: new Date(),
    accepted: false,
    tagIds: ["FJfzAX7zbgQS8jU5XcEk"],
    children: [],
    corrects: 1,
    chooseUname: false,
    deleted: false,
    newChild: true,
    content: "https://arxiv.org/pdf/1311.2901.pdf",
    nodeImage: "",
    proposer: "A_wei",
    summary: "",
    references: [],
    viewers: 1,
    createdAt: new Date(),
    title: "Visualizing and Understanding Convolutional Networks Paper",
    referenceIds: [],
    fullname: "Conner Stevons",
    childType: "Reference",
    parents: [
      {
        label: "",
        node: "OR8UsmsxmeExHG8ekkIY",
        title: "Convolutional Neural Network (CNN)",
      },
    ],
    awards: 0,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FdnSwPNX4gyZN5iQFd9fHBBgnwN82%2FFri%2C%2005%20Feb%202021%2016%3A17%3A04%20GMT.jpg?alt=media&token=fa33055d-5377-4686-87b5-fbf3f8e9dfba",
  },
  {
    documentId: "bkZvknixyiO1Ue7K9htZ",
    tags: ["Data Science"],
    wrongs: 0,
    node: "tKxTypLrxds",
    proposal: "",
    referenceLabels: [],
    updatedAt: new Date(),
    accepted: true,
    tagIds: ["FJfzAX7zbgQS8jU5XcEk"],
    children: [],
    corrects: 1,
    chooseUname: false,
    deleted: false,
    newChild: true,
    content: "https://arxiv.org/pdf/1311.2901.pdf",
    nodeImage: "",
    proposer: "1man",
    summary: "",
    references: [],
    viewers: 1,
    createdAt: new Date(),
    title: "Visualizing and Understanding Convolutional Networks Paper",
    referenceIds: [],
    fullname: "Conner Stevons",
    childType: "Reference",
    parents: [
      {
        label: "",
        node: "OR8UsmsxmeExHG8ekkIY",
        title: "Convolutional Neural Network (CNN)",
      },
    ],
    awards: 0,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FdnSwPNX4gyZN5iQFd9fHBBgnwN82%2FFri%2C%2005%20Feb%202021%2016%3A17%3A04%20GMT.jpg?alt=media&token=fa33055d-5377-4686-87b5-fbf3f8e9dfba",
  },
  {
    documentId: "MD9_aev6q-",
    tags: ["Data Science"],
    wrongs: 0,
    node: "r98BjyFDCe4YyLA3U8ZE",
    proposal: "",
    referenceLabels: [],
    updatedAt: new Date(),
    accepted: true,
    tagIds: ["FJfzAX7zbgQS8jU5XcEk"],
    children: [],
    corrects: 1,
    chooseUname: false,
    deleted: false,
    newChild: true,
    content: "https://arxiv.org/pdf/1311.2901.pdf",
    nodeImage: "",
    proposer: "1man",
    summary: "",
    references: [],
    viewers: 1,
    createdAt: new Date(),
    title: "Visualizing and Understanding Convolutional Networks Paper",
    referenceIds: [],
    fullname: "Conner Stevons",
    childType: "Reference",
    parents: [
      {
        label: "",
        node: "OR8UsmsxmeExHG8ekkIY",
        title: "Convolutional Neural Network (CNN)",
      },
    ],
    awards: 0,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FdnSwPNX4gyZN5iQFd9fHBBgnwN82%2FFri%2C%2005%20Feb%202021%2016%3A17%3A04%20GMT.jpg?alt=media&token=fa33055d-5377-4686-87b5-fbf3f8e9dfba",
  },
];

const conceptVersionsData = { data, collection };

export default conceptVersionsData;
