import { firstWeekMonthDays } from "../../src/utils";

const { firstMonthDay } = firstWeekMonthDays();

export const collection = "monthlyReputations";

const data: any[] = [
  {
    documentd: "015jsmezvToCC9bv7bug",
    createdAt: new Date(),
    firstMonthDay,
    isAdmin: true,
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    uname: "1man",
    updatedAt: new Date(),
    tag: "1Cademy",
    lterm: 0.0,
    ltermDay: 0,
    cnCorrects: 0.0,
    cnInst: 0.0,
    cdCorrects: 0.0,
    cdInst: 0.0,
    qCorrects: 0.0,
    qInst: 0.0,
    pCorrects: 0.0,
    pInst: 0.0,
    sCorrects: 0.0,
    sInst: 0.0,
    aCorrects: 0.0,
    aInst: 0.0,
    rfCorrects: 0.0,
    rfInst: 0.0,
    nCorrects: 0.0,
    nInst: 0.0,
    iCorrects: 0.0,
    iInst: 0.0,
    mCorrects: 0.0,
    mInst: 0.0,
    cnWrongs: 0.0,
    cdWrongs: 0.0,
    qWrongs: 0.0,
    pWrongs: 0.0,
    sWrongs: 0.0,
    aWrongs: 0.0,
    rfWrongs: 0.0,
    nWrongs: 0.0,
    iWrongs: 0.0,
    mWrongs: 0.0,
    negatives: 0.0,
    positives: 0.0,
    totalPoints: 0.0,
  },
  {
    documentId: "01LMgFl66e859MBBJtzu",
    tag: "MockCommunity",
    mCorrects: 46.5,
    negatives: -1,
    tagId: "Ce4YyLA3U8ZEr98BjyFD",
    updatedAt: new Date(),
    dCorrects: 128.5,
    positives: 175,
    ltermDay: 0,
    iWrongs: 0,
    dInst: 0,
    createdAt: new Date(),
    mWrongs: 0,
    iInst: 0,
    iCorrects: 0,
    totalPoints: 176,
    dWrongs: -1,
    firstMonthDay: "2-1-2021",
    lterm: 0,
    uname: "Venkata Sai Suraj Chengalvala",
    isAdmin: true,
    mInst: 0,
  },
  {
    documentId: "yP0FUxYjBj",
    tag: "MockCommunity",
    mCorrects: 46.5,
    negatives: -1,
    tagId: "Ce4YyLZEr9A3U88BjyFD",
    updatedAt: new Date(),
    dCorrects: 128.5,
    positives: 175,
    ltermDay: 0,
    iWrongs: 0,
    dInst: 0,
    createdAt: new Date(),
    mWrongs: 0,
    iInst: 0,
    iCorrects: 0,
    totalPoints: 176,
    dWrongs: -1,
    firstMonthDay: "2-1-2021",
    lterm: 0,
    uname: "A_wei",
    isAdmin: true,
    mInst: 0,
  },
];

const monthlyReputationsData = { data, collection };

export default monthlyReputationsData;
