const collection = "users";

const data: any[] = [
  {
    documentId: "1man",
    createdAt: new Date(),
    clickedCP: true,
    color: "#36cd96",
    blocked: false,
    tagId: "FJfzAX7zbgQS8jU5XcEk",
    background: "Color",
    deCredits: 3,
    country: "United States",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2F1man_Thu%2C%2006%20Feb%202020%2016%3A26%3A40%20GMT.png?alt=media&token=94459dbb-81f9-462a-83ef-62d1129f5851",
    theme: "Dark",
    deInstit: "University of Michigan - Ann Arbor",
    lName: "YeckehZaare",
    uname: "1man",
    lang: "English",
    tag: "Data Science",
    totalPoints: 2013.2699999999993,
    clickedTOS: true,
    deCourse: "SI491",
    fName: "Iman",
    gender: "",
    consented: false,
    imgOrColor: false,
    deMajor: "Information Science",
    userId: "K3DmaX1ZAfXSZ5EzWvz46uJ09fZ2",
    updatedAt: new Date(),
    clickedPP: true,
    sNode: "DVuSVtfgvbfJmQVuHCzD",
    practicing: false,
    email: "oneweb@umich.edu",
    chooseUname: "1man",
  },

  ////////
  {
    documentId: "AMYZH",
    clickedPP: false,
    email: "amyzh@berkeley.edu",
    clickedTOS: false,
    blocked: false,
    clickedCP: false,
    color: "#36cd96",
    lang: "English",
    sNode: "9cccf1ae-2f44-44a1-8fc4-7be648de29f6",
    consented: false,
    deCredits: 3,
    createdAt: {
      _seconds: 1593549019,
      _nanoseconds: 754000000,
    },
    imgOrColor: false,
    tagId: "uYgvhNdciHcuK7ioGZEv",
    uname: "AMYZH",
    theme: "Dark",
    deInstit: "University of California, Berkeley",
    gender: "",
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/onecademy-1.appspot.com/o/ProfilePictures%2FFgkpZ7PxxGacOtStVDmYZ25R1sw1%2FTue%2C%2030%20Jun%202020%2022%3A45%3A34%20GMT.jpg?alt=media&token=cd9f4ca4-2579-4553-8b1c-e960b845d5d9",
    deMajor: "Information Science",
    practicing: false,
    totalPoints: 63,
    fName: "Amy",
    deCourse: "SI691",
    country: "United States",
    lName: "Zhong",
    updatedAt: {
      _seconds: 1593557180,
      _nanoseconds: 947000000,
    },
    tag: "SARS-CoV-2 (COVID-19)",
    userId: "FgkpZ7PxxGacOtStVDmYZ25R1sw1",
  },
  {
    documentId: "A_wei",
    theme: "Dark",
    deMajor: "Information Science",
    education: "Current undergraduate student",
    practicing: false,
    imageUrl: "https://storage.googleapis.com/onecademy-1.appspot.com/ProfilePictures/no-img.png",
    blocked: false,
    ethnicity: ["Asian"],
    createdAt: {
      _seconds: 1616123633,
      _nanoseconds: 69000000,
    },
    deCredits: 3,
    updatedAt: {
      _seconds: 1616123633,
      _nanoseconds: 69000000,
    },
    userId: "so3SC0dltTgsL6ZgWN5I4AOMOth2",
    from: "Word of Mouth",
    clickedPP: false,
    fName: "Alvin",
    tagId: "uYgvhNdciHcuK7ioGZEv",
    country: "United States",
    deInstit: "University of California, Irvine",
    clickedTOS: false,
    color: "#36cd96",
    clickedCP: false,
    uname: "A_wei",
    email: "weiay@uci.edu",
    consented: false,
    city: "Irvine",
    deCourse: "SI691",
    tag: "SARS-CoV-2 (COVID-19)",
    sNode: "cd5YfWXXAnyNZdztjjXv",
    imgOrColor: false,
    stateId: "3924",
    background: "Image",
    lang: "English",
    gender: "Male",
    lName: "Wei",
  },
];

const usersData = { data, collection };

export default usersData;
