const collection = "weeklyReputations";

const data: any[] = [
  {
    documentId: "00oU4hmSNLtbh3b2MQTi",
    firstWeekDay: "3-7-2021",
    positives: 8.9,
    uname: "1man",
    updatedAt: new Date(),
    iWrongs: 0,
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    mCorrects: 3,
    lterm: 0,
    ltermDay: 0,
    iInst: 0,
    mWrongs: 0,
    dInst: 0,
    dWrongs: 2,
    negatives: 2,
    isAdmin: false,
    tag: "1Cademy",
    iCorrects: 0,
    totalPoints: 6.9,
    createdAt: new Date(),
    dCorrects: 5.9,
    mInst: 0,
  },
  {
    documentId: "00wGZF7IkJGEYiHBIerV",
    negatives: 1,
    totalPoints: 26,
    isAdmin: false,
    tag: "1Cademy",
    iCorrects: 1,
    lterm: 0,
    mWrongs: 1,
    ltermDay: 0,
    iWrongs: 0,
    mInst: 0,
    mCorrects: 4,
    createdAt: new Date(),
    iInst: 0,
    firstWeekDay: "1-24-2021",
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    dCorrects: 22,
    uname: "jezzhang",
    dWrongs: 0,
    updatedAt: new Date(),
    positives: 27,
    dInst: 0,
  },
  {
    documentId: "013Kscrca2GL4gBMZ8Bc",
    iInst: 0,
    updatedAt: new Date(),
    uname: "DikshaJothi",
    tag: "1Cademy",
    isAdmin: false,
    mInst: 0,
    firstWeekDay: "6-6-2021",
    dWrongs: 0,
    ltermDay: 0,
    mWrongs: 0,
    negatives: 0,
    mCorrects: 0,
    positives: 1,
    lterm: 0,
    iWrongs: 0,
    dInst: 0,
    totalPoints: 1,
    createdAt: new Date(),
    dCorrects: 1,
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    iCorrects: 0,
  },
];

const weeklyReputationsData = { data, collection };

export default weeklyReputationsData;
