import { firstWeekMonthDays } from "../../src/utils";

const { firstWeekDay } = firstWeekMonthDays();

const collection = "weeklyReputations";

const data: any[] = [
  {
    documentId: "00oU4hmSNLtbh3b2MQTi",
    createdAt: new Date(),
    firstWeekDay,
    isAdmin: true,
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    uname: "1man",
    updatedAt: new Date(),
    tag: "1Cademy",
    lterm: 0.0,
    ltermDay: 0,
    cnCorrects: 0.0,
    cnInst: 0.0,
    cdCorrects: 0.0,
    cdInst: 0.0,
    qCorrects: 0.0,
    qInst: 0.0,
    pCorrects: 0.0,
    pInst: 0.0,
    sCorrects: 0.0,
    sInst: 0.0,
    aCorrects: 0.0,
    aInst: 0.0,
    rfCorrects: 0.0,
    rfInst: 0.0,
    nCorrects: 0.0,
    nInst: 0.0,
    iCorrects: 0.0,
    iInst: 0.0,
    mCorrects: 0.0,
    mInst: 0.0,
    cnWrongs: 0.0,
    cdWrongs: 0.0,
    qWrongs: 0.0,
    pWrongs: 0.0,
    sWrongs: 0.0,
    aWrongs: 0.0,
    rfWrongs: 0.0,
    nWrongs: 0.0,
    iWrongs: 0.0,
    mWrongs: 0.0,
    negatives: 0.0,
    positives: 0.0,
    totalPoints: 0.0,
  },
  {
    documentId: "00wGZF7IkJGEYiHBIerV",
    negatives: 1,
    totalPoints: 26,
    isAdmin: false,
    tag: "1Cademy",
    iCorrects: 1,
    lterm: 0,
    mWrongs: 1,
    ltermDay: 0,
    iWrongs: 0,
    mInst: 0,
    mCorrects: 4,
    createdAt: new Date(),
    iInst: 0,
    firstWeekDay: "1-24-2021",
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    dCorrects: 22,
    uname: "jezzhang",
    dWrongs: 0,
    updatedAt: new Date(),
    positives: 27,
    dInst: 0,
  },
  {
    documentId: "013Kscrca2GL4gBMZ8Bc",
    iInst: 0,
    updatedAt: new Date(),
    uname: "DikshaJothi",
    tag: "1Cademy",
    isAdmin: false,
    mInst: 0,
    firstWeekDay: "6-6-2021",
    dWrongs: 0,
    ltermDay: 0,
    mWrongs: 0,
    negatives: 0,
    mCorrects: 0,
    positives: 1,
    lterm: 0,
    iWrongs: 0,
    dInst: 0,
    totalPoints: 1,
    createdAt: new Date(),
    dCorrects: 1,
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    iCorrects: 0,
  },
  {
    documentId: "AS7KF4pgzv",
    iInst: 0,
    updatedAt: new Date(),
    uname: "A_wei",
    tag: "1Cademy",
    isAdmin: false,
    mInst: 0,
    firstWeekDay: "6-6-2021",
    dWrongs: 0,
    ltermDay: 0,
    mWrongs: 0,
    negatives: 0,
    mCorrects: 0,
    positives: 1,
    lterm: 0,
    iWrongs: 0,
    dInst: 0,
    totalPoints: 1,
    createdAt: new Date(),
    dCorrects: 1,
    tagId: "r98BjyFDCe4YyLA3U8ZE",
    iCorrects: 0,
  },
];

const weeklyReputationsData = { data, collection };

export default weeklyReputationsData;
