version: "3"

services:
  knowledge-next-app:
    container_name: twenty-five-hours-scheduler
    build:
      context: ../
      dockerfile: ./scheduler/Dockerfile
      args:
        ONECADEMYCRED_TYPE: ${ONECADEMYCRED_TYPE}
        ONECADEMYCRED_PRIVATE_KEY_ID: ${ONECADEMYCRED_PRIVATE_KEY_ID}
        ONECADEMYCRED_PRIVATE_KEY: ${ONECADEMYCRED_PRIVATE_KEY}
        ONECADEMYCRED_CLIENT_EMAIL: ${ONECADEMYCRED_CLIENT_EMAIL}
        ONECADEMYCRED_CLIENT_ID: ${ONECADEMYCRED_CLIENT_ID}
        ONECADEMYCRED_AUTH_URI: ${ONECADEMYCRED_AUTH_URI}
        ONECADEMYCRED_TOKEN_URI: ${ONECADEMYCRED_TOKEN_URI}
        ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL: ${ONECADEMYCRED_AUTH_PROVIDER_X509_CERT_URL}
        ONECADEMYCRED_CLIENT_X509_CERT_URL: ${ONECADEMYCRED_CLIENT_X509_CERT_URL}
        ONECADEMYCRED_TYPESENSE_HOST: ${ONECADEMYCRED_TYPESENSE_HOST}
        ONECADEMYCRED_TYPESENSE_PORT: ${ONECADEMYCRED_TYPESENSE_PORT}
        ONECADEMYCRED_TYPESENSE_PROTOCOL: ${ONECADEMYCRED_TYPESENSE_PROTOCOL}
        ONECADEMYCRED_TYPESENSE_APIKEY: ${ONECADEMYCRED_TYPESENSE_APIKEY}
        NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY}
        NEXT_PUBLIC_AUTH_DOMAIN: ${NEXT_PUBLIC_AUTH_DOMAIN}
        NEXT_PUBLIC_DATA_BASE_URL: ${NEXT_PUBLIC_DATA_BASE_URL}
        NEXT_PUBLIC_PROJECT_ID: ${NEXT_PUBLIC_PROJECT_ID}
        NEXT_PUBLIC_STORAGE_BUCKET: ${NEXT_PUBLIC_STORAGE_BUCKET}
        NEXT_PUBLIC_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_APP_ID: ${NEXT_PUBLIC_APP_ID}
        NEXT_PUBLIC_MEASUREMENT_ID: ${NEXT_PUBLIC_MEASUREMENT_ID}
