import { Timestamp } from "firebase-admin/firestore";

import { INodeLink } from "./INodeLink";
import { INodeType } from "./INodeType";
import { IQuestionChoice } from "./IQuestionChoice";

export type INodeVersion = {
  documentId?: string;
  childType?: INodeType;
  choices?: IQuestionChoice[];
  content: string;
  title: string;
  fullname: string;
  children: INodeLink[];
  addedInstitContris?: boolean; // TODO: investigate this, if it run worker even its assigned to true already
  accepted: boolean;
  imageUrl: string;
  updatedAt: Date | Timestamp;
  chooseUname: boolean;
  node: string;
  parents: INodeLink[];
  deleted: boolean;
  corrects: number;
  proposer: string;
  viewers: number;
  proposal: string; // reason of purposed changes
  addedParents?: boolean;
  removedParents?: boolean;
  addedChoices?: boolean;
  deletedChoices?: boolean;
  changedChoices?: boolean;
  changedTitle?: boolean;
  changedContent?: boolean;
  addedImage?: boolean;
  deletedImage?: boolean;
  addedVideo?: boolean;
  deletedVideo?: boolean;
  changedVideo?: boolean;
  addedAudio?: boolean;
  deletedAudio?: boolean;
  changedAudio?: boolean;
  addedReferences?: boolean;
  deletedReferences?: boolean;
  changedReferences?: boolean;
  changedImage?: boolean;
  addedTags?: boolean;
  deletedTags?: boolean;
  changedTags?: boolean;
  addedChildren?: boolean;
  removedChildren?: boolean;
  awards: number;
  summary: string;
  nodeImage?: string;
  nodeVideo?: string;
  nodeAudio?: string;
  subType?: string;
  referenceIds: string[];
  references: string[];
  referenceLabels: string[];
  wrongs: number;
  createdAt: Date | Timestamp;
  tags: string[];
  tagIds: string[];
};
