export const baseReputationObj = ({ points, tag, tagId }: any) => ({
  createdAt: points.createdAt,
  updatedAt: points.updatedAt,
  cnCorrects: parseFloat(points.cnCorrects.toFixed(3)),
  cnInst: parseFloat(points.cnInst.toFixed(3)),
  cnWrongs: parseFloat(points.cnWrongs.toFixed(3)),
  cdCorrects: parseFloat(points.cdCorrects.toFixed(3)),
  cdInst: parseFloat(points.cdInst.toFixed(3)),
  cdWrongs: parseFloat(points.cdWrongs.toFixed(3)),
  qCorrects: parseFloat(points.qCorrects.toFixed(3)),
  qInst: parseFloat(points.qInst.toFixed(3)),
  qWrongs: parseFloat(points.qWrongs.toFixed(3)),
  pCorrects: parseFloat(points.pCorrects.toFixed(3)),
  pInst: parseFloat(points.pInst.toFixed(3)),
  pWrongs: parseFloat(points.pWrongs.toFixed(3)),
  sCorrects: parseFloat(points.sCorrects.toFixed(3)),
  sInst: parseFloat(points.sInst.toFixed(3)),
  sWrongs: parseFloat(points.sWrongs.toFixed(3)),
  aCorrects: parseFloat(points.aCorrects.toFixed(3)),
  aInst: parseFloat(points.aInst.toFixed(3)),
  aWrongs: parseFloat(points.aWrongs.toFixed(3)),
  rfCorrects: parseFloat(points.rfCorrects.toFixed(3)),
  rfInst: parseFloat(points.rfInst.toFixed(3)),
  rfWrongs: parseFloat(points.rfWrongs.toFixed(3)),
  nCorrects: parseFloat(points.nCorrects.toFixed(3)),
  nInst: parseFloat(points.nInst.toFixed(3)),
  nWrongs: parseFloat(points.nWrongs.toFixed(3)),
  iCorrects: parseFloat(points.iCorrects.toFixed(3)),
  iInst: parseFloat(points.iInst.toFixed(3)),
  iWrongs: parseFloat(points.iWrongs.toFixed(3)),
  mCorrects: parseFloat(points.mCorrects.toFixed(3)),
  mInst: parseFloat(points.mInst.toFixed(3)),
  mWrongs: parseFloat(points.mWrongs.toFixed(3)),
  lterm: parseFloat(points.lterm.toFixed(3)),
  ltermDay: parseFloat(points.ltermDay.toFixed(3)),
  positives: parseFloat(points.positives.toFixed(3)),
  negatives: parseFloat(points.negatives.toFixed(3)),
  totalPoints: parseFloat(points.totalPoints.toFixed(3)),
  tag,
  tagId,
});