export const baseReputationObj = ({ points, tag, tagId }: any) => ({
  createdAt: points.createdAt,
  updatedAt: points.updatedAt,
  cnCorrects: parseFloat(points.cnCorrects ? points.cnCorrects.toFixed(3) : 0),
  cnInst: parseFloat(points.cnInst ? points.cnInst.toFixed(3) : 0),
  cnWrongs: parseFloat(points.cnWrongs ? points.cnWrongs.toFixed(3) : 0),
  cdCorrects: parseFloat(points.cdCorrects ? points.cdCorrects.toFixed(3) : 0),
  cdInst: parseFloat(points.cdInst ? points.cdInst.toFixed(3) : 0),
  cdWrongs: parseFloat(points.cdWrongs ? points.cdWrongs.toFixed(3) : 0),
  qCorrects: parseFloat(points.qCorrects ? points.qCorrects.toFixed(3) : 0),
  qInst: parseFloat(points.qInst ? points.qInst.toFixed(3) : 0),
  qWrongs: parseFloat(points.qWrongs ? points.qWrongs.toFixed(3) : 0),
  pCorrects: parseFloat(points.pCorrects ? points.pCorrects.toFixed(3) : 0),
  pInst: parseFloat(points.pInst ? points.pInst.toFixed(3) : 0),
  pWrongs: parseFloat(points.pWrongs ? points.pWrongs.toFixed(3) : 0),
  sCorrects: parseFloat(points.sCorrects ? points.sCorrects.toFixed(3) : 0),
  sInst: parseFloat(points.sInst ? points.sInst.toFixed(3) : 0),
  sWrongs: parseFloat(points.sWrongs ? points.sWrongs.toFixed(3) : 0),
  aCorrects: parseFloat(points.aCorrects ? points.aCorrects.toFixed(3) : 0),
  aInst: parseFloat(points.aInst ? points.aInst.toFixed(3) : 0),
  aWrongs: parseFloat(points.aWrongs ? points.aWrongs.toFixed(3) : 0),
  rfCorrects: parseFloat(points.rfCorrects ? points.rfCorrects.toFixed(3) : 0),
  rfInst: parseFloat(points.rfInst ? points.rfInst.toFixed(3) : 0),
  rfWrongs: parseFloat(points.rfWrongs ? points.rfWrongs.toFixed(3) : 0),
  nCorrects: parseFloat(points.nCorrects ? points.nCorrects.toFixed(3) : 0),
  nInst: parseFloat(points.nInst ? points.nInst.toFixed(3) : 0),
  nWrongs: parseFloat(points.nWrongs ? points.nWrongs.toFixed(3) : 0),
  iCorrects: parseFloat(points.iCorrects ? points.iCorrects.toFixed(3) : 0),
  iInst: parseFloat(points.iInst ? points.iInst.toFixed(3) : 0),
  iWrongs: parseFloat(points.iWrongs ? points.iWrongs.toFixed(3) : 0),
  mCorrects: parseFloat(points.mCorrects ? points.mCorrects.toFixed(3) : 0),
  mInst: parseFloat(points.mInst ? points.mInst.toFixed(3) : 0),
  mWrongs: parseFloat(points.mWrongs ? points.mWrongs.toFixed(3) : 0),
  lterm: parseFloat(points.lterm ? points.lterm.toFixed(3) : 0),
  ltermDay: parseFloat(points.ltermDay ? points.ltermDay.toFixed(3) : 0),
  positives: parseFloat(points.positives ? points.positives.toFixed(3) : 0),
  negatives: parseFloat(points.negatives ? points.negatives.toFixed(3) : 0),
  totalPoints: parseFloat(points.totalPoints ? points.totalPoints.toFixed(3) : 0),
  tag,
  tagId,
});
